// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ApproveSigningRequestPayload approve signing request payload
//
// swagger:model approveSigningRequestPayload
type ApproveSigningRequestPayload struct {

	// action
	// Required: true
	// Enum: [approve reject]
	Action *string `json:"action"`

	// Base64 encoded WebAuthn Authenticator Data
	// Format: byte
	AuthenticatorData strfmt.Base64 `json:"authenticator_data,omitempty"`

	// Base64 encoded WebAuthn Client Data JSON
	// Format: byte
	ClientDataJSON strfmt.Base64 `json:"client_data_json,omitempty"`

	// comment
	Comment string `json:"comment,omitempty"`

	// Base64 encoded WebAuthn Credential ID
	// Format: byte
	CredentialID strfmt.Base64 `json:"credential_id,omitempty"`

	// Base64 encoded WebAuthn Assertion Signature
	// Format: byte
	Signature strfmt.Base64 `json:"signature,omitempty"`
}

// Validate validates this approve signing request payload
func (m *ApproveSigningRequestPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAction(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var approveSigningRequestPayloadTypeActionPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["approve","reject"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		approveSigningRequestPayloadTypeActionPropEnum = append(approveSigningRequestPayloadTypeActionPropEnum, v)
	}
}

const (

	// ApproveSigningRequestPayloadActionApprove captures enum value "approve"
	ApproveSigningRequestPayloadActionApprove string = "approve"

	// ApproveSigningRequestPayloadActionReject captures enum value "reject"
	ApproveSigningRequestPayloadActionReject string = "reject"
)

// prop value enum
func (m *ApproveSigningRequestPayload) validateActionEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, approveSigningRequestPayloadTypeActionPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *ApproveSigningRequestPayload) validateAction(formats strfmt.Registry) error {

	if err := validate.Required("action", "body", m.Action); err != nil {
		return err
	}

	// value enum
	if err := m.validateActionEnum("action", "body", *m.Action); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this approve signing request payload based on context it is used
func (m *ApproveSigningRequestPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ApproveSigningRequestPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ApproveSigningRequestPayload) UnmarshalBinary(b []byte) error {
	var res ApproveSigningRequestPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
