// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateOrganizationResponse create organization response
//
// swagger:model createOrganizationResponse
type CreateOrganizationResponse struct {

	// organization id
	OrganizationID string `json:"organization_id,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this create organization response
func (m *CreateOrganizationResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create organization response based on context it is used
func (m *CreateOrganizationResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateOrganizationResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateOrganizationResponse) UnmarshalBinary(b []byte) error {
	var res CreateOrganizationResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
