// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateVaultResponse create vault response
//
// swagger:model createVaultResponse
type CreateVaultResponse struct {

	// status
	Status string `json:"status,omitempty"`

	// vault id
	// Format: uuid4
	VaultID strfmt.UUID4 `json:"vault_id,omitempty"`
}

// Validate validates this create vault response
func (m *CreateVaultResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateVaultID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateVaultResponse) validateVaultID(formats strfmt.Registry) error {
	if swag.IsZero(m.VaultID) { // not required
		return nil
	}

	if err := validate.FormatOf("vault_id", "body", "uuid4", m.VaultID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create vault response based on context it is used
func (m *CreateVaultResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateVaultResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateVaultResponse) UnmarshalBinary(b []byte) error {
	var res CreateVaultResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
