// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateSigningResponse create signing response
//
// swagger:model createSigningResponse
type CreateSigningResponse struct {

	// request id
	// Format: uuid4
	RequestID strfmt.UUID4 `json:"request_id,omitempty"`

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this create signing response
func (m *CreateSigningResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRequestID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateSigningResponse) validateRequestID(formats strfmt.Registry) error {
	if swag.IsZero(m.RequestID) { // not required
		return nil
	}

	if err := validate.FormatOf("request_id", "body", "uuid4", m.RequestID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create signing response based on context it is used
func (m *CreateSigningResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateSigningResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateSigningResponse) UnmarshalBinary(b []byte) error {
	var res CreateSigningResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
