// Code generated by go-swagger; DO NOT EDIT.

package signing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"

	"github.com/kashguard/go-mpc-vault/internal/types"
)

// NewPostCreateSigningRequestParams creates a new PostCreateSigningRequestParams object
// no default values defined in spec.
func NewPostCreateSigningRequestParams() PostCreateSigningRequestParams {

	return PostCreateSigningRequestParams{}
}

// PostCreateSigningRequestParams contains all the bound params for the post create signing request operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostCreateSigningRequest
type PostCreateSigningRequestParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  In: body
	*/
	Payload *types.CreateSigningRequestPayload
	/*
	  Required: true
	  In: path
	*/
	VaultID string `param:"vaultId"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostCreateSigningRequestParams() beforehand.
func (o *PostCreateSigningRequestParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body types.CreateSigningRequestPayload
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("payload", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Payload = &body
			}
		}
	}
	rVaultID, rhkVaultID, _ := route.Params.GetOK("vaultId")
	if err := o.bindVaultID(rVaultID, rhkVaultID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostCreateSigningRequestParams) Validate(formats strfmt.Registry) error {
	var res []error

	// Payload
	// Required: false

	// body is validated in endpoint
	//if err := o.Payload.Validate(formats); err != nil {
	//  res = append(res, err)
	//}

	// vaultId
	// Required: true
	// Parameter is provided by construction from the route

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindVaultID binds and validates parameter VaultID from path.
func (o *PostCreateSigningRequestParams) bindVaultID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.VaultID = raw

	return nil
}
