swagger: "2.0"
paths:
  /api/v1/vaults/{vaultId}/sign:
    post:
      security:
        - Bearer: []
      tags:
        - signing
      summary: Create a signing request
      operationId: PostCreateSigningRequest
      parameters:
        - name: vaultId
          in: path
          required: true
          type: string
        - name: Payload
          in: body
          schema:
            $ref: ../definitions/signing.yml#/definitions/CreateSigningRequestPayload
      responses:
        "200":
          description: Request Created
          schema:
            $ref: ../definitions/signing.yml#/definitions/CreateSigningResponse
        "400":
          description: Bad Request
        "401":
          description: Unauthorized

  /api/v1/requests/{requestId}/approve:
    post:
      security:
        - Bearer: []
      tags:
        - signing
      summary: Approve or reject a signing request
      operationId: PostApproveSigningRequest
      parameters:
        - name: requestId
          in: path
          required: true
          type: string
        - name: Payload
          in: body
          schema:
            $ref: ../definitions/signing.yml#/definitions/ApproveSigningRequestPayload
      responses:
        "200":
          description: Request Updated
          schema:
            $ref: ../definitions/signing.yml#/definitions/ApproveSigningResponse
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Request Not Found

  /api/v1/requests:
    get:
      security:
        - Bearer: []
      tags:
        - signing
      summary: List signing requests
      operationId: GetListSigningRequests
      parameters:
        - name: status
          in: query
          type: string
          enum: ["pending", "completed", "rejected"]
        - name: vaultId
          in: query
          type: string
        - name: page
          in: query
          type: integer
        - name: limit
          in: query
          type: integer
      responses:
        "200":
          description: Requests
          schema:
            $ref: ../definitions/signing.yml#/definitions/ListSigningRequestsResponse
        "401":
          description: Unauthorized
