// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// Approval is an object representing the database table.
type Approval struct {
	ID        string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	RequestID null.String `boil:"request_id" json:"request_id,omitempty" toml:"request_id" yaml:"request_id,omitempty"`
	UserID    null.String `boil:"user_id" json:"user_id,omitempty" toml:"user_id" yaml:"user_id,omitempty"`
	Action    string      `boil:"action" json:"action" toml:"action" yaml:"action"`
	Comment   null.String `boil:"comment" json:"comment,omitempty" toml:"comment" yaml:"comment,omitempty"`
	CreatedAt null.Time   `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt null.Time   `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`

	R *approvalR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L approvalL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ApprovalColumns = struct {
	ID        string
	RequestID string
	UserID    string
	Action    string
	Comment   string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "id",
	RequestID: "request_id",
	UserID:    "user_id",
	Action:    "action",
	Comment:   "comment",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

var ApprovalTableColumns = struct {
	ID        string
	RequestID string
	UserID    string
	Action    string
	Comment   string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "approvals.id",
	RequestID: "approvals.request_id",
	UserID:    "approvals.user_id",
	Action:    "approvals.action",
	Comment:   "approvals.comment",
	CreatedAt: "approvals.created_at",
	UpdatedAt: "approvals.updated_at",
}

// Generated where

var ApprovalWhere = struct {
	ID        whereHelperstring
	RequestID whereHelpernull_String
	UserID    whereHelpernull_String
	Action    whereHelperstring
	Comment   whereHelpernull_String
	CreatedAt whereHelpernull_Time
	UpdatedAt whereHelpernull_Time
}{
	ID:        whereHelperstring{field: "\"approvals\".\"id\""},
	RequestID: whereHelpernull_String{field: "\"approvals\".\"request_id\""},
	UserID:    whereHelpernull_String{field: "\"approvals\".\"user_id\""},
	Action:    whereHelperstring{field: "\"approvals\".\"action\""},
	Comment:   whereHelpernull_String{field: "\"approvals\".\"comment\""},
	CreatedAt: whereHelpernull_Time{field: "\"approvals\".\"created_at\""},
	UpdatedAt: whereHelpernull_Time{field: "\"approvals\".\"updated_at\""},
}

// ApprovalRels is where relationship names are stored.
var ApprovalRels = struct {
	Request string
	User    string
}{
	Request: "Request",
	User:    "User",
}

// approvalR is where relationships are stored.
type approvalR struct {
	Request *SigningRequest `boil:"Request" json:"Request" toml:"Request" yaml:"Request"`
	User    *User           `boil:"User" json:"User" toml:"User" yaml:"User"`
}

// NewStruct creates a new relationship struct
func (*approvalR) NewStruct() *approvalR {
	return &approvalR{}
}

func (o *Approval) GetRequest() *SigningRequest {
	if o == nil {
		return nil
	}

	return o.R.GetRequest()
}

func (r *approvalR) GetRequest() *SigningRequest {
	if r == nil {
		return nil
	}

	return r.Request
}

func (o *Approval) GetUser() *User {
	if o == nil {
		return nil
	}

	return o.R.GetUser()
}

func (r *approvalR) GetUser() *User {
	if r == nil {
		return nil
	}

	return r.User
}

// approvalL is where Load methods for each relationship are stored.
type approvalL struct{}

var (
	approvalAllColumns            = []string{"id", "request_id", "user_id", "action", "comment", "created_at", "updated_at"}
	approvalColumnsWithoutDefault = []string{"action"}
	approvalColumnsWithDefault    = []string{"id", "request_id", "user_id", "comment", "created_at", "updated_at"}
	approvalPrimaryKeyColumns     = []string{"id"}
	approvalGeneratedColumns      = []string{}
)

type (
	// ApprovalSlice is an alias for a slice of pointers to Approval.
	// This should almost always be used instead of []Approval.
	ApprovalSlice []*Approval

	approvalQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	approvalType                 = reflect.TypeOf(&Approval{})
	approvalMapping              = queries.MakeStructMapping(approvalType)
	approvalPrimaryKeyMapping, _ = queries.BindMapping(approvalType, approvalMapping, approvalPrimaryKeyColumns)
	approvalInsertCacheMut       sync.RWMutex
	approvalInsertCache          = make(map[string]insertCache)
	approvalUpdateCacheMut       sync.RWMutex
	approvalUpdateCache          = make(map[string]updateCache)
	approvalUpsertCacheMut       sync.RWMutex
	approvalUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single approval record from the query.
func (q approvalQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Approval, error) {
	o := &Approval{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for approvals")
	}

	return o, nil
}

// All returns all Approval records from the query.
func (q approvalQuery) All(ctx context.Context, exec boil.ContextExecutor) (ApprovalSlice, error) {
	var o []*Approval

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Approval slice")
	}

	return o, nil
}

// Count returns the count of all Approval records in the query.
func (q approvalQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count approvals rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q approvalQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if approvals exists")
	}

	return count > 0, nil
}

// Request pointed to by the foreign key.
func (o *Approval) Request(mods ...qm.QueryMod) signingRequestQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.RequestID),
	}

	queryMods = append(queryMods, mods...)

	return SigningRequests(queryMods...)
}

// User pointed to by the foreign key.
func (o *Approval) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadRequest allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (approvalL) LoadRequest(ctx context.Context, e boil.ContextExecutor, singular bool, maybeApproval interface{}, mods queries.Applicator) error {
	var slice []*Approval
	var object *Approval

	if singular {
		var ok bool
		object, ok = maybeApproval.(*Approval)
		if !ok {
			object = new(Approval)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeApproval)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeApproval))
			}
		}
	} else {
		s, ok := maybeApproval.(*[]*Approval)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeApproval)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeApproval))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &approvalR{}
		}
		if !queries.IsNil(object.RequestID) {
			args[object.RequestID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &approvalR{}
			}

			if !queries.IsNil(obj.RequestID) {
				args[obj.RequestID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`signing_requests`),
		qm.WhereIn(`signing_requests.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load SigningRequest")
	}

	var resultSlice []*SigningRequest
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice SigningRequest")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for signing_requests")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for signing_requests")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Request = foreign
		if foreign.R == nil {
			foreign.R = &signingRequestR{}
		}
		foreign.R.RequestApprovals = append(foreign.R.RequestApprovals, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.RequestID, foreign.ID) {
				local.R.Request = foreign
				if foreign.R == nil {
					foreign.R = &signingRequestR{}
				}
				foreign.R.RequestApprovals = append(foreign.R.RequestApprovals, local)
				break
			}
		}
	}

	return nil
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (approvalL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeApproval interface{}, mods queries.Applicator) error {
	var slice []*Approval
	var object *Approval

	if singular {
		var ok bool
		object, ok = maybeApproval.(*Approval)
		if !ok {
			object = new(Approval)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeApproval)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeApproval))
			}
		}
	} else {
		s, ok := maybeApproval.(*[]*Approval)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeApproval)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeApproval))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &approvalR{}
		}
		if !queries.IsNil(object.UserID) {
			args[object.UserID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &approvalR{}
			}

			if !queries.IsNil(obj.UserID) {
				args[obj.UserID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.Approvals = append(foreign.R.Approvals, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.UserID, foreign.ID) {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.Approvals = append(foreign.R.Approvals, local)
				break
			}
		}
	}

	return nil
}

// SetRequest of the approval to the related item.
// Sets o.R.Request to related.
// Adds o to related.R.RequestApprovals.
func (o *Approval) SetRequest(ctx context.Context, exec boil.ContextExecutor, insert bool, related *SigningRequest) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"approvals\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"request_id"}),
		strmangle.WhereClause("\"", "\"", 2, approvalPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.RequestID, related.ID)
	if o.R == nil {
		o.R = &approvalR{
			Request: related,
		}
	} else {
		o.R.Request = related
	}

	if related.R == nil {
		related.R = &signingRequestR{
			RequestApprovals: ApprovalSlice{o},
		}
	} else {
		related.R.RequestApprovals = append(related.R.RequestApprovals, o)
	}

	return nil
}

// RemoveRequest relationship.
// Sets o.R.Request to nil.
// Removes o from all passed in related items' relationships struct.
func (o *Approval) RemoveRequest(ctx context.Context, exec boil.ContextExecutor, related *SigningRequest) error {
	var err error

	queries.SetScanner(&o.RequestID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("request_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.Request = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.RequestApprovals {
		if queries.Equal(o.RequestID, ri.RequestID) {
			continue
		}

		ln := len(related.R.RequestApprovals)
		if ln > 1 && i < ln-1 {
			related.R.RequestApprovals[i] = related.R.RequestApprovals[ln-1]
		}
		related.R.RequestApprovals = related.R.RequestApprovals[:ln-1]
		break
	}
	return nil
}

// SetUser of the approval to the related item.
// Sets o.R.User to related.
// Adds o to related.R.Approvals.
func (o *Approval) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"approvals\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, approvalPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.UserID, related.ID)
	if o.R == nil {
		o.R = &approvalR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			Approvals: ApprovalSlice{o},
		}
	} else {
		related.R.Approvals = append(related.R.Approvals, o)
	}

	return nil
}

// RemoveUser relationship.
// Sets o.R.User to nil.
// Removes o from all passed in related items' relationships struct.
func (o *Approval) RemoveUser(ctx context.Context, exec boil.ContextExecutor, related *User) error {
	var err error

	queries.SetScanner(&o.UserID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("user_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.User = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.Approvals {
		if queries.Equal(o.UserID, ri.UserID) {
			continue
		}

		ln := len(related.R.Approvals)
		if ln > 1 && i < ln-1 {
			related.R.Approvals[i] = related.R.Approvals[ln-1]
		}
		related.R.Approvals = related.R.Approvals[:ln-1]
		break
	}
	return nil
}

// Approvals retrieves all the records using an executor.
func Approvals(mods ...qm.QueryMod) approvalQuery {
	mods = append(mods, qm.From("\"approvals\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"approvals\".*"})
	}

	return approvalQuery{q}
}

// FindApproval retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindApproval(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*Approval, error) {
	approvalObj := &Approval{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"approvals\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, approvalObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from approvals")
	}

	return approvalObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Approval) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no approvals provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(approvalColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	approvalInsertCacheMut.RLock()
	cache, cached := approvalInsertCache[key]
	approvalInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			approvalAllColumns,
			approvalColumnsWithDefault,
			approvalColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(approvalType, approvalMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(approvalType, approvalMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"approvals\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"approvals\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into approvals")
	}

	if !cached {
		approvalInsertCacheMut.Lock()
		approvalInsertCache[key] = cache
		approvalInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the Approval.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Approval) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	key := makeCacheKey(columns, nil)
	approvalUpdateCacheMut.RLock()
	cache, cached := approvalUpdateCache[key]
	approvalUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			approvalAllColumns,
			approvalPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update approvals, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"approvals\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, approvalPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(approvalType, approvalMapping, append(wl, approvalPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update approvals row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for approvals")
	}

	if !cached {
		approvalUpdateCacheMut.Lock()
		approvalUpdateCache[key] = cache
		approvalUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q approvalQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for approvals")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for approvals")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ApprovalSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), approvalPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"approvals\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, approvalPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in approval slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all approval")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Approval) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no approvals provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	nzDefaults := queries.NonZeroDefaultSet(approvalColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	approvalUpsertCacheMut.RLock()
	cache, cached := approvalUpsertCache[key]
	approvalUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			approvalAllColumns,
			approvalColumnsWithDefault,
			approvalColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			approvalAllColumns,
			approvalPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert approvals, could not build update column list")
		}

		ret := strmangle.SetComplement(approvalAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(approvalPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert approvals, could not build conflict column list")
			}

			conflict = make([]string, len(approvalPrimaryKeyColumns))
			copy(conflict, approvalPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"approvals\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(approvalType, approvalMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(approvalType, approvalMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert approvals")
	}

	if !cached {
		approvalUpsertCacheMut.Lock()
		approvalUpsertCache[key] = cache
		approvalUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single Approval record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Approval) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Approval provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), approvalPrimaryKeyMapping)
	sql := "DELETE FROM \"approvals\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from approvals")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for approvals")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q approvalQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no approvalQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from approvals")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for approvals")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ApprovalSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), approvalPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"approvals\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, approvalPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from approval slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for approvals")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Approval) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindApproval(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ApprovalSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ApprovalSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), approvalPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"approvals\".* FROM \"approvals\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, approvalPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ApprovalSlice")
	}

	*o = slice

	return nil
}

// ApprovalExists checks if the Approval row exists.
func ApprovalExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"approvals\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if approvals exists")
	}

	return exists, nil
}

// Exists checks if the Approval row exists.
func (o *Approval) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ApprovalExists(ctx, exec, o.ID)
}
