// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// Asset is an object representing the database table.
type Asset struct {
	ID              string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	ChainID         null.String `boil:"chain_id" json:"chain_id,omitempty" toml:"chain_id" yaml:"chain_id,omitempty"`
	Symbol          string      `boil:"symbol" json:"symbol" toml:"symbol" yaml:"symbol"`
	Name            string      `boil:"name" json:"name" toml:"name" yaml:"name"`
	Type            string      `boil:"type" json:"type" toml:"type" yaml:"type"`
	ContractAddress null.String `boil:"contract_address" json:"contract_address,omitempty" toml:"contract_address" yaml:"contract_address,omitempty"`
	Decimals        int         `boil:"decimals" json:"decimals" toml:"decimals" yaml:"decimals"`
	IconURL         null.String `boil:"icon_url" json:"icon_url,omitempty" toml:"icon_url" yaml:"icon_url,omitempty"`
	IsActive        null.Bool   `boil:"is_active" json:"is_active,omitempty" toml:"is_active" yaml:"is_active,omitempty"`
	CreatedAt       null.Time   `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt       null.Time   `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`

	R *assetR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L assetL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var AssetColumns = struct {
	ID              string
	ChainID         string
	Symbol          string
	Name            string
	Type            string
	ContractAddress string
	Decimals        string
	IconURL         string
	IsActive        string
	CreatedAt       string
	UpdatedAt       string
}{
	ID:              "id",
	ChainID:         "chain_id",
	Symbol:          "symbol",
	Name:            "name",
	Type:            "type",
	ContractAddress: "contract_address",
	Decimals:        "decimals",
	IconURL:         "icon_url",
	IsActive:        "is_active",
	CreatedAt:       "created_at",
	UpdatedAt:       "updated_at",
}

var AssetTableColumns = struct {
	ID              string
	ChainID         string
	Symbol          string
	Name            string
	Type            string
	ContractAddress string
	Decimals        string
	IconURL         string
	IsActive        string
	CreatedAt       string
	UpdatedAt       string
}{
	ID:              "assets.id",
	ChainID:         "assets.chain_id",
	Symbol:          "assets.symbol",
	Name:            "assets.name",
	Type:            "assets.type",
	ContractAddress: "assets.contract_address",
	Decimals:        "assets.decimals",
	IconURL:         "assets.icon_url",
	IsActive:        "assets.is_active",
	CreatedAt:       "assets.created_at",
	UpdatedAt:       "assets.updated_at",
}

// Generated where

type whereHelperint struct{ field string }

func (w whereHelperint) EQ(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint) NEQ(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint) LT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint) LTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint) GT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint) GTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint) IN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint) NIN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

var AssetWhere = struct {
	ID              whereHelperstring
	ChainID         whereHelpernull_String
	Symbol          whereHelperstring
	Name            whereHelperstring
	Type            whereHelperstring
	ContractAddress whereHelpernull_String
	Decimals        whereHelperint
	IconURL         whereHelpernull_String
	IsActive        whereHelpernull_Bool
	CreatedAt       whereHelpernull_Time
	UpdatedAt       whereHelpernull_Time
}{
	ID:              whereHelperstring{field: "\"assets\".\"id\""},
	ChainID:         whereHelpernull_String{field: "\"assets\".\"chain_id\""},
	Symbol:          whereHelperstring{field: "\"assets\".\"symbol\""},
	Name:            whereHelperstring{field: "\"assets\".\"name\""},
	Type:            whereHelperstring{field: "\"assets\".\"type\""},
	ContractAddress: whereHelpernull_String{field: "\"assets\".\"contract_address\""},
	Decimals:        whereHelperint{field: "\"assets\".\"decimals\""},
	IconURL:         whereHelpernull_String{field: "\"assets\".\"icon_url\""},
	IsActive:        whereHelpernull_Bool{field: "\"assets\".\"is_active\""},
	CreatedAt:       whereHelpernull_Time{field: "\"assets\".\"created_at\""},
	UpdatedAt:       whereHelpernull_Time{field: "\"assets\".\"updated_at\""},
}

// AssetRels is where relationship names are stored.
var AssetRels = struct {
	Chain          string
	SpendingLimits string
	WalletBalances string
}{
	Chain:          "Chain",
	SpendingLimits: "SpendingLimits",
	WalletBalances: "WalletBalances",
}

// assetR is where relationships are stored.
type assetR struct {
	Chain          *Chain             `boil:"Chain" json:"Chain" toml:"Chain" yaml:"Chain"`
	SpendingLimits SpendingLimitSlice `boil:"SpendingLimits" json:"SpendingLimits" toml:"SpendingLimits" yaml:"SpendingLimits"`
	WalletBalances WalletBalanceSlice `boil:"WalletBalances" json:"WalletBalances" toml:"WalletBalances" yaml:"WalletBalances"`
}

// NewStruct creates a new relationship struct
func (*assetR) NewStruct() *assetR {
	return &assetR{}
}

func (o *Asset) GetChain() *Chain {
	if o == nil {
		return nil
	}

	return o.R.GetChain()
}

func (r *assetR) GetChain() *Chain {
	if r == nil {
		return nil
	}

	return r.Chain
}

func (o *Asset) GetSpendingLimits() SpendingLimitSlice {
	if o == nil {
		return nil
	}

	return o.R.GetSpendingLimits()
}

func (r *assetR) GetSpendingLimits() SpendingLimitSlice {
	if r == nil {
		return nil
	}

	return r.SpendingLimits
}

func (o *Asset) GetWalletBalances() WalletBalanceSlice {
	if o == nil {
		return nil
	}

	return o.R.GetWalletBalances()
}

func (r *assetR) GetWalletBalances() WalletBalanceSlice {
	if r == nil {
		return nil
	}

	return r.WalletBalances
}

// assetL is where Load methods for each relationship are stored.
type assetL struct{}

var (
	assetAllColumns            = []string{"id", "chain_id", "symbol", "name", "type", "contract_address", "decimals", "icon_url", "is_active", "created_at", "updated_at"}
	assetColumnsWithoutDefault = []string{"symbol", "name", "type"}
	assetColumnsWithDefault    = []string{"id", "chain_id", "contract_address", "decimals", "icon_url", "is_active", "created_at", "updated_at"}
	assetPrimaryKeyColumns     = []string{"id"}
	assetGeneratedColumns      = []string{}
)

type (
	// AssetSlice is an alias for a slice of pointers to Asset.
	// This should almost always be used instead of []Asset.
	AssetSlice []*Asset

	assetQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	assetType                 = reflect.TypeOf(&Asset{})
	assetMapping              = queries.MakeStructMapping(assetType)
	assetPrimaryKeyMapping, _ = queries.BindMapping(assetType, assetMapping, assetPrimaryKeyColumns)
	assetInsertCacheMut       sync.RWMutex
	assetInsertCache          = make(map[string]insertCache)
	assetUpdateCacheMut       sync.RWMutex
	assetUpdateCache          = make(map[string]updateCache)
	assetUpsertCacheMut       sync.RWMutex
	assetUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single asset record from the query.
func (q assetQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Asset, error) {
	o := &Asset{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for assets")
	}

	return o, nil
}

// All returns all Asset records from the query.
func (q assetQuery) All(ctx context.Context, exec boil.ContextExecutor) (AssetSlice, error) {
	var o []*Asset

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Asset slice")
	}

	return o, nil
}

// Count returns the count of all Asset records in the query.
func (q assetQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count assets rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q assetQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if assets exists")
	}

	return count > 0, nil
}

// Chain pointed to by the foreign key.
func (o *Asset) Chain(mods ...qm.QueryMod) chainQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ChainID),
	}

	queryMods = append(queryMods, mods...)

	return Chains(queryMods...)
}

// SpendingLimits retrieves all the spending_limit's SpendingLimits with an executor.
func (o *Asset) SpendingLimits(mods ...qm.QueryMod) spendingLimitQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"spending_limits\".\"asset_id\"=?", o.ID),
	)

	return SpendingLimits(queryMods...)
}

// WalletBalances retrieves all the wallet_balance's WalletBalances with an executor.
func (o *Asset) WalletBalances(mods ...qm.QueryMod) walletBalanceQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"wallet_balances\".\"asset_id\"=?", o.ID),
	)

	return WalletBalances(queryMods...)
}

// LoadChain allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (assetL) LoadChain(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAsset interface{}, mods queries.Applicator) error {
	var slice []*Asset
	var object *Asset

	if singular {
		var ok bool
		object, ok = maybeAsset.(*Asset)
		if !ok {
			object = new(Asset)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeAsset)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeAsset))
			}
		}
	} else {
		s, ok := maybeAsset.(*[]*Asset)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeAsset)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeAsset))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &assetR{}
		}
		if !queries.IsNil(object.ChainID) {
			args[object.ChainID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &assetR{}
			}

			if !queries.IsNil(obj.ChainID) {
				args[obj.ChainID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`chains`),
		qm.WhereIn(`chains.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Chain")
	}

	var resultSlice []*Chain
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Chain")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for chains")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for chains")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Chain = foreign
		if foreign.R == nil {
			foreign.R = &chainR{}
		}
		foreign.R.Assets = append(foreign.R.Assets, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.ChainID, foreign.ID) {
				local.R.Chain = foreign
				if foreign.R == nil {
					foreign.R = &chainR{}
				}
				foreign.R.Assets = append(foreign.R.Assets, local)
				break
			}
		}
	}

	return nil
}

// LoadSpendingLimits allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (assetL) LoadSpendingLimits(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAsset interface{}, mods queries.Applicator) error {
	var slice []*Asset
	var object *Asset

	if singular {
		var ok bool
		object, ok = maybeAsset.(*Asset)
		if !ok {
			object = new(Asset)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeAsset)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeAsset))
			}
		}
	} else {
		s, ok := maybeAsset.(*[]*Asset)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeAsset)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeAsset))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &assetR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &assetR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`spending_limits`),
		qm.WhereIn(`spending_limits.asset_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load spending_limits")
	}

	var resultSlice []*SpendingLimit
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice spending_limits")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on spending_limits")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for spending_limits")
	}

	if singular {
		object.R.SpendingLimits = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &spendingLimitR{}
			}
			foreign.R.Asset = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.AssetID) {
				local.R.SpendingLimits = append(local.R.SpendingLimits, foreign)
				if foreign.R == nil {
					foreign.R = &spendingLimitR{}
				}
				foreign.R.Asset = local
				break
			}
		}
	}

	return nil
}

// LoadWalletBalances allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (assetL) LoadWalletBalances(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAsset interface{}, mods queries.Applicator) error {
	var slice []*Asset
	var object *Asset

	if singular {
		var ok bool
		object, ok = maybeAsset.(*Asset)
		if !ok {
			object = new(Asset)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeAsset)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeAsset))
			}
		}
	} else {
		s, ok := maybeAsset.(*[]*Asset)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeAsset)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeAsset))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &assetR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &assetR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`wallet_balances`),
		qm.WhereIn(`wallet_balances.asset_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load wallet_balances")
	}

	var resultSlice []*WalletBalance
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice wallet_balances")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on wallet_balances")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for wallet_balances")
	}

	if singular {
		object.R.WalletBalances = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &walletBalanceR{}
			}
			foreign.R.Asset = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.AssetID) {
				local.R.WalletBalances = append(local.R.WalletBalances, foreign)
				if foreign.R == nil {
					foreign.R = &walletBalanceR{}
				}
				foreign.R.Asset = local
				break
			}
		}
	}

	return nil
}

// SetChain of the asset to the related item.
// Sets o.R.Chain to related.
// Adds o to related.R.Assets.
func (o *Asset) SetChain(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Chain) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"assets\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"chain_id"}),
		strmangle.WhereClause("\"", "\"", 2, assetPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.ChainID, related.ID)
	if o.R == nil {
		o.R = &assetR{
			Chain: related,
		}
	} else {
		o.R.Chain = related
	}

	if related.R == nil {
		related.R = &chainR{
			Assets: AssetSlice{o},
		}
	} else {
		related.R.Assets = append(related.R.Assets, o)
	}

	return nil
}

// RemoveChain relationship.
// Sets o.R.Chain to nil.
// Removes o from all passed in related items' relationships struct.
func (o *Asset) RemoveChain(ctx context.Context, exec boil.ContextExecutor, related *Chain) error {
	var err error

	queries.SetScanner(&o.ChainID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("chain_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.Chain = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.Assets {
		if queries.Equal(o.ChainID, ri.ChainID) {
			continue
		}

		ln := len(related.R.Assets)
		if ln > 1 && i < ln-1 {
			related.R.Assets[i] = related.R.Assets[ln-1]
		}
		related.R.Assets = related.R.Assets[:ln-1]
		break
	}
	return nil
}

// AddSpendingLimits adds the given related objects to the existing relationships
// of the asset, optionally inserting them as new records.
// Appends related to o.R.SpendingLimits.
// Sets related.R.Asset appropriately.
func (o *Asset) AddSpendingLimits(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*SpendingLimit) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.AssetID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"spending_limits\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"asset_id"}),
				strmangle.WhereClause("\"", "\"", 2, spendingLimitPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.AssetID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &assetR{
			SpendingLimits: related,
		}
	} else {
		o.R.SpendingLimits = append(o.R.SpendingLimits, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &spendingLimitR{
				Asset: o,
			}
		} else {
			rel.R.Asset = o
		}
	}
	return nil
}

// SetSpendingLimits removes all previously related items of the
// asset replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Asset's SpendingLimits accordingly.
// Replaces o.R.SpendingLimits with related.
// Sets related.R.Asset's SpendingLimits accordingly.
func (o *Asset) SetSpendingLimits(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*SpendingLimit) error {
	query := "update \"spending_limits\" set \"asset_id\" = null where \"asset_id\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.SpendingLimits {
			queries.SetScanner(&rel.AssetID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.Asset = nil
		}
		o.R.SpendingLimits = nil
	}

	return o.AddSpendingLimits(ctx, exec, insert, related...)
}

// RemoveSpendingLimits relationships from objects passed in.
// Removes related items from R.SpendingLimits (uses pointer comparison, removal does not keep order)
// Sets related.R.Asset.
func (o *Asset) RemoveSpendingLimits(ctx context.Context, exec boil.ContextExecutor, related ...*SpendingLimit) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.AssetID, nil)
		if rel.R != nil {
			rel.R.Asset = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("asset_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.SpendingLimits {
			if rel != ri {
				continue
			}

			ln := len(o.R.SpendingLimits)
			if ln > 1 && i < ln-1 {
				o.R.SpendingLimits[i] = o.R.SpendingLimits[ln-1]
			}
			o.R.SpendingLimits = o.R.SpendingLimits[:ln-1]
			break
		}
	}

	return nil
}

// AddWalletBalances adds the given related objects to the existing relationships
// of the asset, optionally inserting them as new records.
// Appends related to o.R.WalletBalances.
// Sets related.R.Asset appropriately.
func (o *Asset) AddWalletBalances(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*WalletBalance) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.AssetID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"wallet_balances\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"asset_id"}),
				strmangle.WhereClause("\"", "\"", 2, walletBalancePrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.AssetID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &assetR{
			WalletBalances: related,
		}
	} else {
		o.R.WalletBalances = append(o.R.WalletBalances, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &walletBalanceR{
				Asset: o,
			}
		} else {
			rel.R.Asset = o
		}
	}
	return nil
}

// SetWalletBalances removes all previously related items of the
// asset replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Asset's WalletBalances accordingly.
// Replaces o.R.WalletBalances with related.
// Sets related.R.Asset's WalletBalances accordingly.
func (o *Asset) SetWalletBalances(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*WalletBalance) error {
	query := "update \"wallet_balances\" set \"asset_id\" = null where \"asset_id\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.WalletBalances {
			queries.SetScanner(&rel.AssetID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.Asset = nil
		}
		o.R.WalletBalances = nil
	}

	return o.AddWalletBalances(ctx, exec, insert, related...)
}

// RemoveWalletBalances relationships from objects passed in.
// Removes related items from R.WalletBalances (uses pointer comparison, removal does not keep order)
// Sets related.R.Asset.
func (o *Asset) RemoveWalletBalances(ctx context.Context, exec boil.ContextExecutor, related ...*WalletBalance) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.AssetID, nil)
		if rel.R != nil {
			rel.R.Asset = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("asset_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.WalletBalances {
			if rel != ri {
				continue
			}

			ln := len(o.R.WalletBalances)
			if ln > 1 && i < ln-1 {
				o.R.WalletBalances[i] = o.R.WalletBalances[ln-1]
			}
			o.R.WalletBalances = o.R.WalletBalances[:ln-1]
			break
		}
	}

	return nil
}

// Assets retrieves all the records using an executor.
func Assets(mods ...qm.QueryMod) assetQuery {
	mods = append(mods, qm.From("\"assets\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"assets\".*"})
	}

	return assetQuery{q}
}

// FindAsset retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindAsset(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*Asset, error) {
	assetObj := &Asset{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"assets\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, assetObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from assets")
	}

	return assetObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Asset) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no assets provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(assetColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	assetInsertCacheMut.RLock()
	cache, cached := assetInsertCache[key]
	assetInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			assetAllColumns,
			assetColumnsWithDefault,
			assetColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(assetType, assetMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(assetType, assetMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"assets\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"assets\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into assets")
	}

	if !cached {
		assetInsertCacheMut.Lock()
		assetInsertCache[key] = cache
		assetInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the Asset.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Asset) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	key := makeCacheKey(columns, nil)
	assetUpdateCacheMut.RLock()
	cache, cached := assetUpdateCache[key]
	assetUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			assetAllColumns,
			assetPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update assets, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"assets\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, assetPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(assetType, assetMapping, append(wl, assetPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update assets row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for assets")
	}

	if !cached {
		assetUpdateCacheMut.Lock()
		assetUpdateCache[key] = cache
		assetUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q assetQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for assets")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for assets")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o AssetSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), assetPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"assets\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, assetPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in asset slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all asset")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Asset) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no assets provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	nzDefaults := queries.NonZeroDefaultSet(assetColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	assetUpsertCacheMut.RLock()
	cache, cached := assetUpsertCache[key]
	assetUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			assetAllColumns,
			assetColumnsWithDefault,
			assetColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			assetAllColumns,
			assetPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert assets, could not build update column list")
		}

		ret := strmangle.SetComplement(assetAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(assetPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert assets, could not build conflict column list")
			}

			conflict = make([]string, len(assetPrimaryKeyColumns))
			copy(conflict, assetPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"assets\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(assetType, assetMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(assetType, assetMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert assets")
	}

	if !cached {
		assetUpsertCacheMut.Lock()
		assetUpsertCache[key] = cache
		assetUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single Asset record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Asset) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Asset provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), assetPrimaryKeyMapping)
	sql := "DELETE FROM \"assets\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from assets")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for assets")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q assetQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no assetQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from assets")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for assets")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o AssetSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), assetPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"assets\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, assetPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from asset slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for assets")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Asset) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindAsset(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AssetSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := AssetSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), assetPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"assets\".* FROM \"assets\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, assetPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in AssetSlice")
	}

	*o = slice

	return nil
}

// AssetExists checks if the Asset row exists.
func AssetExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"assets\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if assets exists")
	}

	return exists, nil
}

// Exists checks if the Asset row exists.
func (o *Asset) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return AssetExists(ctx, exec, o.ID)
}
