// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/aarondl/randomize"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testSigningRequests(t *testing.T) {
	t.Parallel()

	query := SigningRequests()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testSigningRequestsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SigningRequest{}
	if err = randomize.Struct(seed, o, signingRequestDBTypes, true, signingRequestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningRequest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := SigningRequests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSigningRequestsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SigningRequest{}
	if err = randomize.Struct(seed, o, signingRequestDBTypes, true, signingRequestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningRequest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := SigningRequests().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := SigningRequests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSigningRequestsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SigningRequest{}
	if err = randomize.Struct(seed, o, signingRequestDBTypes, true, signingRequestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningRequest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SigningRequestSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := SigningRequests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSigningRequestsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SigningRequest{}
	if err = randomize.Struct(seed, o, signingRequestDBTypes, true, signingRequestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningRequest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := SigningRequestExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if SigningRequest exists: %s", err)
	}
	if !e {
		t.Errorf("Expected SigningRequestExists to return true, but got false.")
	}
}

func testSigningRequestsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SigningRequest{}
	if err = randomize.Struct(seed, o, signingRequestDBTypes, true, signingRequestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningRequest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	signingRequestFound, err := FindSigningRequest(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if signingRequestFound == nil {
		t.Error("want a record, got nil")
	}
}

func testSigningRequestsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SigningRequest{}
	if err = randomize.Struct(seed, o, signingRequestDBTypes, true, signingRequestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningRequest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = SigningRequests().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testSigningRequestsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SigningRequest{}
	if err = randomize.Struct(seed, o, signingRequestDBTypes, true, signingRequestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningRequest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := SigningRequests().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testSigningRequestsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	signingRequestOne := &SigningRequest{}
	signingRequestTwo := &SigningRequest{}
	if err = randomize.Struct(seed, signingRequestOne, signingRequestDBTypes, false, signingRequestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningRequest struct: %s", err)
	}
	if err = randomize.Struct(seed, signingRequestTwo, signingRequestDBTypes, false, signingRequestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningRequest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = signingRequestOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = signingRequestTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := SigningRequests().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testSigningRequestsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	signingRequestOne := &SigningRequest{}
	signingRequestTwo := &SigningRequest{}
	if err = randomize.Struct(seed, signingRequestOne, signingRequestDBTypes, false, signingRequestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningRequest struct: %s", err)
	}
	if err = randomize.Struct(seed, signingRequestTwo, signingRequestDBTypes, false, signingRequestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningRequest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = signingRequestOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = signingRequestTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SigningRequests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testSigningRequestsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SigningRequest{}
	if err = randomize.Struct(seed, o, signingRequestDBTypes, true, signingRequestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningRequest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SigningRequests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSigningRequestsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SigningRequest{}
	if err = randomize.Struct(seed, o, signingRequestDBTypes, true); err != nil {
		t.Errorf("Unable to randomize SigningRequest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(strmangle.SetMerge(signingRequestPrimaryKeyColumns, signingRequestColumnsWithoutDefault)...)); err != nil {
		t.Error(err)
	}

	count, err := SigningRequests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSigningRequestToManyRequestApprovals(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a SigningRequest
	var b, c Approval

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, signingRequestDBTypes, true, signingRequestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningRequest struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, approvalDBTypes, false, approvalColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, approvalDBTypes, false, approvalColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&b.RequestID, a.ID)
	queries.Assign(&c.RequestID, a.ID)
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.RequestApprovals().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if queries.Equal(v.RequestID, b.RequestID) {
			bFound = true
		}
		if queries.Equal(v.RequestID, c.RequestID) {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := SigningRequestSlice{&a}
	if err = a.L.LoadRequestApprovals(ctx, tx, false, (*[]*SigningRequest)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.RequestApprovals); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.RequestApprovals = nil
	if err = a.L.LoadRequestApprovals(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.RequestApprovals); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testSigningRequestToManyAddOpRequestApprovals(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a SigningRequest
	var b, c, d, e Approval

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, signingRequestDBTypes, false, strmangle.SetComplement(signingRequestPrimaryKeyColumns, signingRequestColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Approval{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, approvalDBTypes, false, strmangle.SetComplement(approvalPrimaryKeyColumns, approvalColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Approval{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddRequestApprovals(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if !queries.Equal(a.ID, first.RequestID) {
			t.Error("foreign key was wrong value", a.ID, first.RequestID)
		}
		if !queries.Equal(a.ID, second.RequestID) {
			t.Error("foreign key was wrong value", a.ID, second.RequestID)
		}

		if first.R.Request != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Request != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.RequestApprovals[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.RequestApprovals[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.RequestApprovals().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testSigningRequestToManySetOpRequestApprovals(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a SigningRequest
	var b, c, d, e Approval

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, signingRequestDBTypes, false, strmangle.SetComplement(signingRequestPrimaryKeyColumns, signingRequestColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Approval{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, approvalDBTypes, false, strmangle.SetComplement(approvalPrimaryKeyColumns, approvalColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.SetRequestApprovals(ctx, tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.RequestApprovals().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetRequestApprovals(ctx, tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.RequestApprovals().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.RequestID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.RequestID) {
		t.Error("want c's foreign key value to be nil")
	}
	if !queries.Equal(a.ID, d.RequestID) {
		t.Error("foreign key was wrong value", a.ID, d.RequestID)
	}
	if !queries.Equal(a.ID, e.RequestID) {
		t.Error("foreign key was wrong value", a.ID, e.RequestID)
	}

	if b.R.Request != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Request != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Request != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.Request != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if a.R.RequestApprovals[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.RequestApprovals[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testSigningRequestToManyRemoveOpRequestApprovals(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a SigningRequest
	var b, c, d, e Approval

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, signingRequestDBTypes, false, strmangle.SetComplement(signingRequestPrimaryKeyColumns, signingRequestColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Approval{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, approvalDBTypes, false, strmangle.SetComplement(approvalPrimaryKeyColumns, approvalColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.AddRequestApprovals(ctx, tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.RequestApprovals().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemoveRequestApprovals(ctx, tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.RequestApprovals().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.RequestID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.RequestID) {
		t.Error("want c's foreign key value to be nil")
	}

	if b.R.Request != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Request != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Request != &a {
		t.Error("relationship to a should have been preserved")
	}
	if e.R.Request != &a {
		t.Error("relationship to a should have been preserved")
	}

	if len(a.R.RequestApprovals) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.RequestApprovals[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.RequestApprovals[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testSigningRequestToOneUserUsingInitiator(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local SigningRequest
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, signingRequestDBTypes, true, signingRequestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningRequest struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.InitiatorID, foreign.ID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Initiator().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := SigningRequestSlice{&local}
	if err = local.L.LoadInitiator(ctx, tx, false, (*[]*SigningRequest)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Initiator == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Initiator = nil
	if err = local.L.LoadInitiator(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Initiator == nil {
		t.Error("struct should have been eager loaded")
	}

}

func testSigningRequestToOneVaultUsingVault(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local SigningRequest
	var foreign Vault

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, signingRequestDBTypes, true, signingRequestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningRequest struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, vaultDBTypes, false, vaultColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Vault struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.VaultID, foreign.ID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Vault().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := SigningRequestSlice{&local}
	if err = local.L.LoadVault(ctx, tx, false, (*[]*SigningRequest)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Vault == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Vault = nil
	if err = local.L.LoadVault(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Vault == nil {
		t.Error("struct should have been eager loaded")
	}

}

func testSigningRequestToOneWalletUsingWallet(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local SigningRequest
	var foreign Wallet

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, signingRequestDBTypes, true, signingRequestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningRequest struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, walletDBTypes, false, walletColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Wallet struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.WalletID, foreign.ID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Wallet().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := SigningRequestSlice{&local}
	if err = local.L.LoadWallet(ctx, tx, false, (*[]*SigningRequest)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Wallet == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Wallet = nil
	if err = local.L.LoadWallet(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Wallet == nil {
		t.Error("struct should have been eager loaded")
	}

}

func testSigningRequestToOneSetOpUserUsingInitiator(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a SigningRequest
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, signingRequestDBTypes, false, strmangle.SetComplement(signingRequestPrimaryKeyColumns, signingRequestColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetInitiator(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Initiator != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.InitiatorSigningRequests[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.InitiatorID, x.ID) {
			t.Error("foreign key was wrong value", a.InitiatorID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.InitiatorID))
		reflect.Indirect(reflect.ValueOf(&a.InitiatorID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.InitiatorID, x.ID) {
			t.Error("foreign key was wrong value", a.InitiatorID, x.ID)
		}
	}
}

func testSigningRequestToOneRemoveOpUserUsingInitiator(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a SigningRequest
	var b User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, signingRequestDBTypes, false, strmangle.SetComplement(signingRequestPrimaryKeyColumns, signingRequestColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetInitiator(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveInitiator(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.Initiator().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.Initiator != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.InitiatorID) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.InitiatorSigningRequests) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testSigningRequestToOneSetOpVaultUsingVault(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a SigningRequest
	var b, c Vault

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, signingRequestDBTypes, false, strmangle.SetComplement(signingRequestPrimaryKeyColumns, signingRequestColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, vaultDBTypes, false, strmangle.SetComplement(vaultPrimaryKeyColumns, vaultColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, vaultDBTypes, false, strmangle.SetComplement(vaultPrimaryKeyColumns, vaultColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Vault{&b, &c} {
		err = a.SetVault(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Vault != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.SigningRequests[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.VaultID, x.ID) {
			t.Error("foreign key was wrong value", a.VaultID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.VaultID))
		reflect.Indirect(reflect.ValueOf(&a.VaultID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.VaultID, x.ID) {
			t.Error("foreign key was wrong value", a.VaultID, x.ID)
		}
	}
}

func testSigningRequestToOneRemoveOpVaultUsingVault(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a SigningRequest
	var b Vault

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, signingRequestDBTypes, false, strmangle.SetComplement(signingRequestPrimaryKeyColumns, signingRequestColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, vaultDBTypes, false, strmangle.SetComplement(vaultPrimaryKeyColumns, vaultColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetVault(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveVault(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.Vault().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.Vault != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.VaultID) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.SigningRequests) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testSigningRequestToOneSetOpWalletUsingWallet(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a SigningRequest
	var b, c Wallet

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, signingRequestDBTypes, false, strmangle.SetComplement(signingRequestPrimaryKeyColumns, signingRequestColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, walletDBTypes, false, strmangle.SetComplement(walletPrimaryKeyColumns, walletColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, walletDBTypes, false, strmangle.SetComplement(walletPrimaryKeyColumns, walletColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Wallet{&b, &c} {
		err = a.SetWallet(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Wallet != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.SigningRequests[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.WalletID, x.ID) {
			t.Error("foreign key was wrong value", a.WalletID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.WalletID))
		reflect.Indirect(reflect.ValueOf(&a.WalletID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.WalletID, x.ID) {
			t.Error("foreign key was wrong value", a.WalletID, x.ID)
		}
	}
}

func testSigningRequestToOneRemoveOpWalletUsingWallet(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a SigningRequest
	var b Wallet

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, signingRequestDBTypes, false, strmangle.SetComplement(signingRequestPrimaryKeyColumns, signingRequestColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, walletDBTypes, false, strmangle.SetComplement(walletPrimaryKeyColumns, walletColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetWallet(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveWallet(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.Wallet().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.Wallet != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.WalletID) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.SigningRequests) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testSigningRequestsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SigningRequest{}
	if err = randomize.Struct(seed, o, signingRequestDBTypes, true, signingRequestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningRequest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSigningRequestsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SigningRequest{}
	if err = randomize.Struct(seed, o, signingRequestDBTypes, true, signingRequestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningRequest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SigningRequestSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSigningRequestsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SigningRequest{}
	if err = randomize.Struct(seed, o, signingRequestDBTypes, true, signingRequestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningRequest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := SigningRequests().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	signingRequestDBTypes = map[string]string{`ID`: `uuid`, `VaultID`: `uuid`, `WalletID`: `uuid`, `InitiatorID`: `uuid`, `TXData`: `text`, `TXHash`: `character varying`, `Amount`: `numeric`, `ToAddress`: `character varying`, `Note`: `text`, `Status`: `character varying`, `MPCSessionID`: `character varying`, `Signature`: `text`, `CreatedAt`: `timestamp with time zone`, `UpdatedAt`: `timestamp with time zone`}
	_                     = bytes.MinRead
)

func testSigningRequestsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(signingRequestPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(signingRequestAllColumns) == len(signingRequestPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &SigningRequest{}
	if err = randomize.Struct(seed, o, signingRequestDBTypes, true, signingRequestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningRequest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SigningRequests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, signingRequestDBTypes, true, signingRequestPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize SigningRequest struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testSigningRequestsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(signingRequestAllColumns) == len(signingRequestPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &SigningRequest{}
	if err = randomize.Struct(seed, o, signingRequestDBTypes, true, signingRequestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SigningRequest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SigningRequests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, signingRequestDBTypes, true, signingRequestPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize SigningRequest struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(signingRequestAllColumns, signingRequestPrimaryKeyColumns) {
		fields = signingRequestAllColumns
	} else {
		fields = strmangle.SetComplement(
			signingRequestAllColumns,
			signingRequestPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := SigningRequestSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testSigningRequestsUpsert(t *testing.T) {
	t.Parallel()

	if len(signingRequestAllColumns) == len(signingRequestPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := SigningRequest{}
	if err = randomize.Struct(seed, &o, signingRequestDBTypes, true); err != nil {
		t.Errorf("Unable to randomize SigningRequest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert SigningRequest: %s", err)
	}

	count, err := SigningRequests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, signingRequestDBTypes, false, signingRequestPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize SigningRequest struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert SigningRequest: %s", err)
	}

	count, err = SigningRequests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
