// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/aarondl/randomize"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testSpendingLimits(t *testing.T) {
	t.Parallel()

	query := SpendingLimits()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testSpendingLimitsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SpendingLimit{}
	if err = randomize.Struct(seed, o, spendingLimitDBTypes, true, spendingLimitColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SpendingLimit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := SpendingLimits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSpendingLimitsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SpendingLimit{}
	if err = randomize.Struct(seed, o, spendingLimitDBTypes, true, spendingLimitColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SpendingLimit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := SpendingLimits().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := SpendingLimits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSpendingLimitsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SpendingLimit{}
	if err = randomize.Struct(seed, o, spendingLimitDBTypes, true, spendingLimitColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SpendingLimit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SpendingLimitSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := SpendingLimits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSpendingLimitsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SpendingLimit{}
	if err = randomize.Struct(seed, o, spendingLimitDBTypes, true, spendingLimitColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SpendingLimit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := SpendingLimitExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if SpendingLimit exists: %s", err)
	}
	if !e {
		t.Errorf("Expected SpendingLimitExists to return true, but got false.")
	}
}

func testSpendingLimitsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SpendingLimit{}
	if err = randomize.Struct(seed, o, spendingLimitDBTypes, true, spendingLimitColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SpendingLimit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	spendingLimitFound, err := FindSpendingLimit(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if spendingLimitFound == nil {
		t.Error("want a record, got nil")
	}
}

func testSpendingLimitsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SpendingLimit{}
	if err = randomize.Struct(seed, o, spendingLimitDBTypes, true, spendingLimitColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SpendingLimit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = SpendingLimits().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testSpendingLimitsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SpendingLimit{}
	if err = randomize.Struct(seed, o, spendingLimitDBTypes, true, spendingLimitColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SpendingLimit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := SpendingLimits().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testSpendingLimitsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	spendingLimitOne := &SpendingLimit{}
	spendingLimitTwo := &SpendingLimit{}
	if err = randomize.Struct(seed, spendingLimitOne, spendingLimitDBTypes, false, spendingLimitColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SpendingLimit struct: %s", err)
	}
	if err = randomize.Struct(seed, spendingLimitTwo, spendingLimitDBTypes, false, spendingLimitColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SpendingLimit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = spendingLimitOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = spendingLimitTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := SpendingLimits().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testSpendingLimitsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	spendingLimitOne := &SpendingLimit{}
	spendingLimitTwo := &SpendingLimit{}
	if err = randomize.Struct(seed, spendingLimitOne, spendingLimitDBTypes, false, spendingLimitColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SpendingLimit struct: %s", err)
	}
	if err = randomize.Struct(seed, spendingLimitTwo, spendingLimitDBTypes, false, spendingLimitColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SpendingLimit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = spendingLimitOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = spendingLimitTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SpendingLimits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testSpendingLimitsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SpendingLimit{}
	if err = randomize.Struct(seed, o, spendingLimitDBTypes, true, spendingLimitColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SpendingLimit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SpendingLimits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSpendingLimitsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SpendingLimit{}
	if err = randomize.Struct(seed, o, spendingLimitDBTypes, true); err != nil {
		t.Errorf("Unable to randomize SpendingLimit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(strmangle.SetMerge(spendingLimitPrimaryKeyColumns, spendingLimitColumnsWithoutDefault)...)); err != nil {
		t.Error(err)
	}

	count, err := SpendingLimits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSpendingLimitToOneAssetUsingAsset(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local SpendingLimit
	var foreign Asset

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, spendingLimitDBTypes, true, spendingLimitColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SpendingLimit struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, assetDBTypes, false, assetColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Asset struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.AssetID, foreign.ID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Asset().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := SpendingLimitSlice{&local}
	if err = local.L.LoadAsset(ctx, tx, false, (*[]*SpendingLimit)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Asset == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Asset = nil
	if err = local.L.LoadAsset(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Asset == nil {
		t.Error("struct should have been eager loaded")
	}

}

func testSpendingLimitToOneVaultUsingVault(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local SpendingLimit
	var foreign Vault

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, spendingLimitDBTypes, true, spendingLimitColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SpendingLimit struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, vaultDBTypes, false, vaultColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Vault struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.VaultID, foreign.ID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Vault().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := SpendingLimitSlice{&local}
	if err = local.L.LoadVault(ctx, tx, false, (*[]*SpendingLimit)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Vault == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Vault = nil
	if err = local.L.LoadVault(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Vault == nil {
		t.Error("struct should have been eager loaded")
	}

}

func testSpendingLimitToOneSetOpAssetUsingAsset(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a SpendingLimit
	var b, c Asset

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, spendingLimitDBTypes, false, strmangle.SetComplement(spendingLimitPrimaryKeyColumns, spendingLimitColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, assetDBTypes, false, strmangle.SetComplement(assetPrimaryKeyColumns, assetColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, assetDBTypes, false, strmangle.SetComplement(assetPrimaryKeyColumns, assetColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Asset{&b, &c} {
		err = a.SetAsset(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Asset != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.SpendingLimits[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.AssetID, x.ID) {
			t.Error("foreign key was wrong value", a.AssetID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.AssetID))
		reflect.Indirect(reflect.ValueOf(&a.AssetID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.AssetID, x.ID) {
			t.Error("foreign key was wrong value", a.AssetID, x.ID)
		}
	}
}

func testSpendingLimitToOneRemoveOpAssetUsingAsset(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a SpendingLimit
	var b Asset

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, spendingLimitDBTypes, false, strmangle.SetComplement(spendingLimitPrimaryKeyColumns, spendingLimitColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, assetDBTypes, false, strmangle.SetComplement(assetPrimaryKeyColumns, assetColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetAsset(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveAsset(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.Asset().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.Asset != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.AssetID) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.SpendingLimits) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testSpendingLimitToOneSetOpVaultUsingVault(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a SpendingLimit
	var b, c Vault

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, spendingLimitDBTypes, false, strmangle.SetComplement(spendingLimitPrimaryKeyColumns, spendingLimitColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, vaultDBTypes, false, strmangle.SetComplement(vaultPrimaryKeyColumns, vaultColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, vaultDBTypes, false, strmangle.SetComplement(vaultPrimaryKeyColumns, vaultColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Vault{&b, &c} {
		err = a.SetVault(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Vault != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.SpendingLimits[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.VaultID, x.ID) {
			t.Error("foreign key was wrong value", a.VaultID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.VaultID))
		reflect.Indirect(reflect.ValueOf(&a.VaultID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.VaultID, x.ID) {
			t.Error("foreign key was wrong value", a.VaultID, x.ID)
		}
	}
}

func testSpendingLimitToOneRemoveOpVaultUsingVault(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a SpendingLimit
	var b Vault

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, spendingLimitDBTypes, false, strmangle.SetComplement(spendingLimitPrimaryKeyColumns, spendingLimitColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, vaultDBTypes, false, strmangle.SetComplement(vaultPrimaryKeyColumns, vaultColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetVault(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveVault(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.Vault().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.Vault != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.VaultID) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.SpendingLimits) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testSpendingLimitsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SpendingLimit{}
	if err = randomize.Struct(seed, o, spendingLimitDBTypes, true, spendingLimitColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SpendingLimit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSpendingLimitsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SpendingLimit{}
	if err = randomize.Struct(seed, o, spendingLimitDBTypes, true, spendingLimitColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SpendingLimit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SpendingLimitSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSpendingLimitsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SpendingLimit{}
	if err = randomize.Struct(seed, o, spendingLimitDBTypes, true, spendingLimitColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SpendingLimit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := SpendingLimits().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	spendingLimitDBTypes = map[string]string{`ID`: `uuid`, `VaultID`: `uuid`, `AssetID`: `uuid`, `Amount`: `numeric`, `WindowSeconds`: `integer`, `Action`: `character varying`, `CreatedAt`: `timestamp with time zone`, `UpdatedAt`: `timestamp with time zone`}
	_                    = bytes.MinRead
)

func testSpendingLimitsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(spendingLimitPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(spendingLimitAllColumns) == len(spendingLimitPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &SpendingLimit{}
	if err = randomize.Struct(seed, o, spendingLimitDBTypes, true, spendingLimitColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SpendingLimit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SpendingLimits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, spendingLimitDBTypes, true, spendingLimitPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize SpendingLimit struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testSpendingLimitsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(spendingLimitAllColumns) == len(spendingLimitPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &SpendingLimit{}
	if err = randomize.Struct(seed, o, spendingLimitDBTypes, true, spendingLimitColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SpendingLimit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SpendingLimits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, spendingLimitDBTypes, true, spendingLimitPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize SpendingLimit struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(spendingLimitAllColumns, spendingLimitPrimaryKeyColumns) {
		fields = spendingLimitAllColumns
	} else {
		fields = strmangle.SetComplement(
			spendingLimitAllColumns,
			spendingLimitPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := SpendingLimitSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testSpendingLimitsUpsert(t *testing.T) {
	t.Parallel()

	if len(spendingLimitAllColumns) == len(spendingLimitPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := SpendingLimit{}
	if err = randomize.Struct(seed, &o, spendingLimitDBTypes, true); err != nil {
		t.Errorf("Unable to randomize SpendingLimit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert SpendingLimit: %s", err)
	}

	count, err := SpendingLimits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, spendingLimitDBTypes, false, spendingLimitPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize SpendingLimit struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert SpendingLimit: %s", err)
	}

	count, err = SpendingLimits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
