// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/aarondl/randomize"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testWallets(t *testing.T) {
	t.Parallel()

	query := Wallets()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testWalletsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Wallet{}
	if err = randomize.Struct(seed, o, walletDBTypes, true, walletColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Wallet struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Wallets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testWalletsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Wallet{}
	if err = randomize.Struct(seed, o, walletDBTypes, true, walletColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Wallet struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Wallets().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Wallets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testWalletsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Wallet{}
	if err = randomize.Struct(seed, o, walletDBTypes, true, walletColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Wallet struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := WalletSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Wallets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testWalletsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Wallet{}
	if err = randomize.Struct(seed, o, walletDBTypes, true, walletColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Wallet struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := WalletExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Wallet exists: %s", err)
	}
	if !e {
		t.Errorf("Expected WalletExists to return true, but got false.")
	}
}

func testWalletsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Wallet{}
	if err = randomize.Struct(seed, o, walletDBTypes, true, walletColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Wallet struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	walletFound, err := FindWallet(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if walletFound == nil {
		t.Error("want a record, got nil")
	}
}

func testWalletsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Wallet{}
	if err = randomize.Struct(seed, o, walletDBTypes, true, walletColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Wallet struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Wallets().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testWalletsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Wallet{}
	if err = randomize.Struct(seed, o, walletDBTypes, true, walletColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Wallet struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Wallets().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testWalletsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	walletOne := &Wallet{}
	walletTwo := &Wallet{}
	if err = randomize.Struct(seed, walletOne, walletDBTypes, false, walletColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Wallet struct: %s", err)
	}
	if err = randomize.Struct(seed, walletTwo, walletDBTypes, false, walletColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Wallet struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = walletOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = walletTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Wallets().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testWalletsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	walletOne := &Wallet{}
	walletTwo := &Wallet{}
	if err = randomize.Struct(seed, walletOne, walletDBTypes, false, walletColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Wallet struct: %s", err)
	}
	if err = randomize.Struct(seed, walletTwo, walletDBTypes, false, walletColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Wallet struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = walletOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = walletTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Wallets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testWalletsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Wallet{}
	if err = randomize.Struct(seed, o, walletDBTypes, true, walletColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Wallet struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Wallets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testWalletsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Wallet{}
	if err = randomize.Struct(seed, o, walletDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Wallet struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(strmangle.SetMerge(walletPrimaryKeyColumns, walletColumnsWithoutDefault)...)); err != nil {
		t.Error(err)
	}

	count, err := Wallets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testWalletToManySigningRequests(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Wallet
	var b, c SigningRequest

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, walletDBTypes, true, walletColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Wallet struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, signingRequestDBTypes, false, signingRequestColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, signingRequestDBTypes, false, signingRequestColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&b.WalletID, a.ID)
	queries.Assign(&c.WalletID, a.ID)
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.SigningRequests().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if queries.Equal(v.WalletID, b.WalletID) {
			bFound = true
		}
		if queries.Equal(v.WalletID, c.WalletID) {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := WalletSlice{&a}
	if err = a.L.LoadSigningRequests(ctx, tx, false, (*[]*Wallet)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.SigningRequests); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.SigningRequests = nil
	if err = a.L.LoadSigningRequests(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.SigningRequests); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testWalletToManyWalletBalances(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Wallet
	var b, c WalletBalance

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, walletDBTypes, true, walletColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Wallet struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, walletBalanceDBTypes, false, walletBalanceColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, walletBalanceDBTypes, false, walletBalanceColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&b.WalletID, a.ID)
	queries.Assign(&c.WalletID, a.ID)
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.WalletBalances().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if queries.Equal(v.WalletID, b.WalletID) {
			bFound = true
		}
		if queries.Equal(v.WalletID, c.WalletID) {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := WalletSlice{&a}
	if err = a.L.LoadWalletBalances(ctx, tx, false, (*[]*Wallet)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.WalletBalances); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.WalletBalances = nil
	if err = a.L.LoadWalletBalances(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.WalletBalances); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testWalletToManyAddOpSigningRequests(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Wallet
	var b, c, d, e SigningRequest

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, walletDBTypes, false, strmangle.SetComplement(walletPrimaryKeyColumns, walletColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*SigningRequest{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, signingRequestDBTypes, false, strmangle.SetComplement(signingRequestPrimaryKeyColumns, signingRequestColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*SigningRequest{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddSigningRequests(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if !queries.Equal(a.ID, first.WalletID) {
			t.Error("foreign key was wrong value", a.ID, first.WalletID)
		}
		if !queries.Equal(a.ID, second.WalletID) {
			t.Error("foreign key was wrong value", a.ID, second.WalletID)
		}

		if first.R.Wallet != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Wallet != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.SigningRequests[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.SigningRequests[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.SigningRequests().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testWalletToManySetOpSigningRequests(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Wallet
	var b, c, d, e SigningRequest

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, walletDBTypes, false, strmangle.SetComplement(walletPrimaryKeyColumns, walletColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*SigningRequest{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, signingRequestDBTypes, false, strmangle.SetComplement(signingRequestPrimaryKeyColumns, signingRequestColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.SetSigningRequests(ctx, tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.SigningRequests().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetSigningRequests(ctx, tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.SigningRequests().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.WalletID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.WalletID) {
		t.Error("want c's foreign key value to be nil")
	}
	if !queries.Equal(a.ID, d.WalletID) {
		t.Error("foreign key was wrong value", a.ID, d.WalletID)
	}
	if !queries.Equal(a.ID, e.WalletID) {
		t.Error("foreign key was wrong value", a.ID, e.WalletID)
	}

	if b.R.Wallet != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Wallet != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Wallet != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.Wallet != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if a.R.SigningRequests[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.SigningRequests[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testWalletToManyRemoveOpSigningRequests(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Wallet
	var b, c, d, e SigningRequest

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, walletDBTypes, false, strmangle.SetComplement(walletPrimaryKeyColumns, walletColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*SigningRequest{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, signingRequestDBTypes, false, strmangle.SetComplement(signingRequestPrimaryKeyColumns, signingRequestColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.AddSigningRequests(ctx, tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.SigningRequests().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemoveSigningRequests(ctx, tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.SigningRequests().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.WalletID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.WalletID) {
		t.Error("want c's foreign key value to be nil")
	}

	if b.R.Wallet != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Wallet != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Wallet != &a {
		t.Error("relationship to a should have been preserved")
	}
	if e.R.Wallet != &a {
		t.Error("relationship to a should have been preserved")
	}

	if len(a.R.SigningRequests) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.SigningRequests[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.SigningRequests[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testWalletToManyAddOpWalletBalances(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Wallet
	var b, c, d, e WalletBalance

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, walletDBTypes, false, strmangle.SetComplement(walletPrimaryKeyColumns, walletColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*WalletBalance{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, walletBalanceDBTypes, false, strmangle.SetComplement(walletBalancePrimaryKeyColumns, walletBalanceColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*WalletBalance{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddWalletBalances(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if !queries.Equal(a.ID, first.WalletID) {
			t.Error("foreign key was wrong value", a.ID, first.WalletID)
		}
		if !queries.Equal(a.ID, second.WalletID) {
			t.Error("foreign key was wrong value", a.ID, second.WalletID)
		}

		if first.R.Wallet != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Wallet != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.WalletBalances[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.WalletBalances[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.WalletBalances().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testWalletToManySetOpWalletBalances(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Wallet
	var b, c, d, e WalletBalance

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, walletDBTypes, false, strmangle.SetComplement(walletPrimaryKeyColumns, walletColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*WalletBalance{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, walletBalanceDBTypes, false, strmangle.SetComplement(walletBalancePrimaryKeyColumns, walletBalanceColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.SetWalletBalances(ctx, tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.WalletBalances().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetWalletBalances(ctx, tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.WalletBalances().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.WalletID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.WalletID) {
		t.Error("want c's foreign key value to be nil")
	}
	if !queries.Equal(a.ID, d.WalletID) {
		t.Error("foreign key was wrong value", a.ID, d.WalletID)
	}
	if !queries.Equal(a.ID, e.WalletID) {
		t.Error("foreign key was wrong value", a.ID, e.WalletID)
	}

	if b.R.Wallet != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Wallet != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Wallet != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.Wallet != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if a.R.WalletBalances[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.WalletBalances[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testWalletToManyRemoveOpWalletBalances(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Wallet
	var b, c, d, e WalletBalance

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, walletDBTypes, false, strmangle.SetComplement(walletPrimaryKeyColumns, walletColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*WalletBalance{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, walletBalanceDBTypes, false, strmangle.SetComplement(walletBalancePrimaryKeyColumns, walletBalanceColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.AddWalletBalances(ctx, tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.WalletBalances().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemoveWalletBalances(ctx, tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.WalletBalances().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.WalletID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.WalletID) {
		t.Error("want c's foreign key value to be nil")
	}

	if b.R.Wallet != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Wallet != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Wallet != &a {
		t.Error("relationship to a should have been preserved")
	}
	if e.R.Wallet != &a {
		t.Error("relationship to a should have been preserved")
	}

	if len(a.R.WalletBalances) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.WalletBalances[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.WalletBalances[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testWalletToOneChainUsingChain(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Wallet
	var foreign Chain

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, walletDBTypes, true, walletColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Wallet struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, chainDBTypes, false, chainColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Chain struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.ChainID, foreign.ID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Chain().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := WalletSlice{&local}
	if err = local.L.LoadChain(ctx, tx, false, (*[]*Wallet)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Chain == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Chain = nil
	if err = local.L.LoadChain(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Chain == nil {
		t.Error("struct should have been eager loaded")
	}

}

func testWalletToOneVaultUsingVault(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Wallet
	var foreign Vault

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, walletDBTypes, true, walletColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Wallet struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, vaultDBTypes, false, vaultColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Vault struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.VaultID, foreign.ID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Vault().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := WalletSlice{&local}
	if err = local.L.LoadVault(ctx, tx, false, (*[]*Wallet)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Vault == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Vault = nil
	if err = local.L.LoadVault(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Vault == nil {
		t.Error("struct should have been eager loaded")
	}

}

func testWalletToOneSetOpChainUsingChain(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Wallet
	var b, c Chain

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, walletDBTypes, false, strmangle.SetComplement(walletPrimaryKeyColumns, walletColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, chainDBTypes, false, strmangle.SetComplement(chainPrimaryKeyColumns, chainColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, chainDBTypes, false, strmangle.SetComplement(chainPrimaryKeyColumns, chainColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Chain{&b, &c} {
		err = a.SetChain(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Chain != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Wallets[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.ChainID, x.ID) {
			t.Error("foreign key was wrong value", a.ChainID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.ChainID))
		reflect.Indirect(reflect.ValueOf(&a.ChainID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.ChainID, x.ID) {
			t.Error("foreign key was wrong value", a.ChainID, x.ID)
		}
	}
}

func testWalletToOneRemoveOpChainUsingChain(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Wallet
	var b Chain

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, walletDBTypes, false, strmangle.SetComplement(walletPrimaryKeyColumns, walletColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, chainDBTypes, false, strmangle.SetComplement(chainPrimaryKeyColumns, chainColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetChain(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveChain(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.Chain().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.Chain != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.ChainID) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.Wallets) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testWalletToOneSetOpVaultUsingVault(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Wallet
	var b, c Vault

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, walletDBTypes, false, strmangle.SetComplement(walletPrimaryKeyColumns, walletColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, vaultDBTypes, false, strmangle.SetComplement(vaultPrimaryKeyColumns, vaultColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, vaultDBTypes, false, strmangle.SetComplement(vaultPrimaryKeyColumns, vaultColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Vault{&b, &c} {
		err = a.SetVault(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Vault != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Wallets[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.VaultID, x.ID) {
			t.Error("foreign key was wrong value", a.VaultID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.VaultID))
		reflect.Indirect(reflect.ValueOf(&a.VaultID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.VaultID, x.ID) {
			t.Error("foreign key was wrong value", a.VaultID, x.ID)
		}
	}
}

func testWalletToOneRemoveOpVaultUsingVault(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Wallet
	var b Vault

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, walletDBTypes, false, strmangle.SetComplement(walletPrimaryKeyColumns, walletColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, vaultDBTypes, false, strmangle.SetComplement(vaultPrimaryKeyColumns, vaultColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetVault(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveVault(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.Vault().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.Vault != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.VaultID) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.Wallets) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testWalletsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Wallet{}
	if err = randomize.Struct(seed, o, walletDBTypes, true, walletColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Wallet struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testWalletsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Wallet{}
	if err = randomize.Struct(seed, o, walletDBTypes, true, walletColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Wallet struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := WalletSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testWalletsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Wallet{}
	if err = randomize.Struct(seed, o, walletDBTypes, true, walletColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Wallet struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Wallets().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	walletDBTypes = map[string]string{`ID`: `uuid`, `VaultID`: `uuid`, `ChainID`: `character varying`, `KeyID`: `character varying`, `Address`: `character varying`, `DerivePath`: `character varying`, `DeriveIndex`: `integer`, `CreatedAt`: `timestamp with time zone`, `UpdatedAt`: `timestamp with time zone`}
	_             = bytes.MinRead
)

func testWalletsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(walletPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(walletAllColumns) == len(walletPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Wallet{}
	if err = randomize.Struct(seed, o, walletDBTypes, true, walletColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Wallet struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Wallets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, walletDBTypes, true, walletPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Wallet struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testWalletsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(walletAllColumns) == len(walletPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Wallet{}
	if err = randomize.Struct(seed, o, walletDBTypes, true, walletColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Wallet struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Wallets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, walletDBTypes, true, walletPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Wallet struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(walletAllColumns, walletPrimaryKeyColumns) {
		fields = walletAllColumns
	} else {
		fields = strmangle.SetComplement(
			walletAllColumns,
			walletPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := WalletSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testWalletsUpsert(t *testing.T) {
	t.Parallel()

	if len(walletAllColumns) == len(walletPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Wallet{}
	if err = randomize.Struct(seed, &o, walletDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Wallet struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Wallet: %s", err)
	}

	count, err := Wallets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, walletDBTypes, false, walletPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Wallet struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Wallet: %s", err)
	}

	count, err = Wallets().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
