// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// Wallet is an object representing the database table.
type Wallet struct {
	ID          string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	VaultID     null.String `boil:"vault_id" json:"vault_id,omitempty" toml:"vault_id" yaml:"vault_id,omitempty"`
	ChainID     null.String `boil:"chain_id" json:"chain_id,omitempty" toml:"chain_id" yaml:"chain_id,omitempty"`
	KeyID       string      `boil:"key_id" json:"key_id" toml:"key_id" yaml:"key_id"`
	Address     string      `boil:"address" json:"address" toml:"address" yaml:"address"`
	DerivePath  string      `boil:"derive_path" json:"derive_path" toml:"derive_path" yaml:"derive_path"`
	DeriveIndex int         `boil:"derive_index" json:"derive_index" toml:"derive_index" yaml:"derive_index"`
	CreatedAt   null.Time   `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt   null.Time   `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`

	R *walletR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L walletL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var WalletColumns = struct {
	ID          string
	VaultID     string
	ChainID     string
	KeyID       string
	Address     string
	DerivePath  string
	DeriveIndex string
	CreatedAt   string
	UpdatedAt   string
}{
	ID:          "id",
	VaultID:     "vault_id",
	ChainID:     "chain_id",
	KeyID:       "key_id",
	Address:     "address",
	DerivePath:  "derive_path",
	DeriveIndex: "derive_index",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
}

var WalletTableColumns = struct {
	ID          string
	VaultID     string
	ChainID     string
	KeyID       string
	Address     string
	DerivePath  string
	DeriveIndex string
	CreatedAt   string
	UpdatedAt   string
}{
	ID:          "wallets.id",
	VaultID:     "wallets.vault_id",
	ChainID:     "wallets.chain_id",
	KeyID:       "wallets.key_id",
	Address:     "wallets.address",
	DerivePath:  "wallets.derive_path",
	DeriveIndex: "wallets.derive_index",
	CreatedAt:   "wallets.created_at",
	UpdatedAt:   "wallets.updated_at",
}

// Generated where

var WalletWhere = struct {
	ID          whereHelperstring
	VaultID     whereHelpernull_String
	ChainID     whereHelpernull_String
	KeyID       whereHelperstring
	Address     whereHelperstring
	DerivePath  whereHelperstring
	DeriveIndex whereHelperint
	CreatedAt   whereHelpernull_Time
	UpdatedAt   whereHelpernull_Time
}{
	ID:          whereHelperstring{field: "\"wallets\".\"id\""},
	VaultID:     whereHelpernull_String{field: "\"wallets\".\"vault_id\""},
	ChainID:     whereHelpernull_String{field: "\"wallets\".\"chain_id\""},
	KeyID:       whereHelperstring{field: "\"wallets\".\"key_id\""},
	Address:     whereHelperstring{field: "\"wallets\".\"address\""},
	DerivePath:  whereHelperstring{field: "\"wallets\".\"derive_path\""},
	DeriveIndex: whereHelperint{field: "\"wallets\".\"derive_index\""},
	CreatedAt:   whereHelpernull_Time{field: "\"wallets\".\"created_at\""},
	UpdatedAt:   whereHelpernull_Time{field: "\"wallets\".\"updated_at\""},
}

// WalletRels is where relationship names are stored.
var WalletRels = struct {
	Chain           string
	Vault           string
	SigningRequests string
	WalletBalances  string
}{
	Chain:           "Chain",
	Vault:           "Vault",
	SigningRequests: "SigningRequests",
	WalletBalances:  "WalletBalances",
}

// walletR is where relationships are stored.
type walletR struct {
	Chain           *Chain              `boil:"Chain" json:"Chain" toml:"Chain" yaml:"Chain"`
	Vault           *Vault              `boil:"Vault" json:"Vault" toml:"Vault" yaml:"Vault"`
	SigningRequests SigningRequestSlice `boil:"SigningRequests" json:"SigningRequests" toml:"SigningRequests" yaml:"SigningRequests"`
	WalletBalances  WalletBalanceSlice  `boil:"WalletBalances" json:"WalletBalances" toml:"WalletBalances" yaml:"WalletBalances"`
}

// NewStruct creates a new relationship struct
func (*walletR) NewStruct() *walletR {
	return &walletR{}
}

func (o *Wallet) GetChain() *Chain {
	if o == nil {
		return nil
	}

	return o.R.GetChain()
}

func (r *walletR) GetChain() *Chain {
	if r == nil {
		return nil
	}

	return r.Chain
}

func (o *Wallet) GetVault() *Vault {
	if o == nil {
		return nil
	}

	return o.R.GetVault()
}

func (r *walletR) GetVault() *Vault {
	if r == nil {
		return nil
	}

	return r.Vault
}

func (o *Wallet) GetSigningRequests() SigningRequestSlice {
	if o == nil {
		return nil
	}

	return o.R.GetSigningRequests()
}

func (r *walletR) GetSigningRequests() SigningRequestSlice {
	if r == nil {
		return nil
	}

	return r.SigningRequests
}

func (o *Wallet) GetWalletBalances() WalletBalanceSlice {
	if o == nil {
		return nil
	}

	return o.R.GetWalletBalances()
}

func (r *walletR) GetWalletBalances() WalletBalanceSlice {
	if r == nil {
		return nil
	}

	return r.WalletBalances
}

// walletL is where Load methods for each relationship are stored.
type walletL struct{}

var (
	walletAllColumns            = []string{"id", "vault_id", "chain_id", "key_id", "address", "derive_path", "derive_index", "created_at", "updated_at"}
	walletColumnsWithoutDefault = []string{"key_id", "address", "derive_path", "derive_index"}
	walletColumnsWithDefault    = []string{"id", "vault_id", "chain_id", "created_at", "updated_at"}
	walletPrimaryKeyColumns     = []string{"id"}
	walletGeneratedColumns      = []string{}
)

type (
	// WalletSlice is an alias for a slice of pointers to Wallet.
	// This should almost always be used instead of []Wallet.
	WalletSlice []*Wallet

	walletQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	walletType                 = reflect.TypeOf(&Wallet{})
	walletMapping              = queries.MakeStructMapping(walletType)
	walletPrimaryKeyMapping, _ = queries.BindMapping(walletType, walletMapping, walletPrimaryKeyColumns)
	walletInsertCacheMut       sync.RWMutex
	walletInsertCache          = make(map[string]insertCache)
	walletUpdateCacheMut       sync.RWMutex
	walletUpdateCache          = make(map[string]updateCache)
	walletUpsertCacheMut       sync.RWMutex
	walletUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single wallet record from the query.
func (q walletQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Wallet, error) {
	o := &Wallet{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for wallets")
	}

	return o, nil
}

// All returns all Wallet records from the query.
func (q walletQuery) All(ctx context.Context, exec boil.ContextExecutor) (WalletSlice, error) {
	var o []*Wallet

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Wallet slice")
	}

	return o, nil
}

// Count returns the count of all Wallet records in the query.
func (q walletQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count wallets rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q walletQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if wallets exists")
	}

	return count > 0, nil
}

// Chain pointed to by the foreign key.
func (o *Wallet) Chain(mods ...qm.QueryMod) chainQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ChainID),
	}

	queryMods = append(queryMods, mods...)

	return Chains(queryMods...)
}

// Vault pointed to by the foreign key.
func (o *Wallet) Vault(mods ...qm.QueryMod) vaultQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.VaultID),
	}

	queryMods = append(queryMods, mods...)

	return Vaults(queryMods...)
}

// SigningRequests retrieves all the signing_request's SigningRequests with an executor.
func (o *Wallet) SigningRequests(mods ...qm.QueryMod) signingRequestQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"signing_requests\".\"wallet_id\"=?", o.ID),
	)

	return SigningRequests(queryMods...)
}

// WalletBalances retrieves all the wallet_balance's WalletBalances with an executor.
func (o *Wallet) WalletBalances(mods ...qm.QueryMod) walletBalanceQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"wallet_balances\".\"wallet_id\"=?", o.ID),
	)

	return WalletBalances(queryMods...)
}

// LoadChain allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (walletL) LoadChain(ctx context.Context, e boil.ContextExecutor, singular bool, maybeWallet interface{}, mods queries.Applicator) error {
	var slice []*Wallet
	var object *Wallet

	if singular {
		var ok bool
		object, ok = maybeWallet.(*Wallet)
		if !ok {
			object = new(Wallet)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeWallet)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeWallet))
			}
		}
	} else {
		s, ok := maybeWallet.(*[]*Wallet)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeWallet)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeWallet))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &walletR{}
		}
		if !queries.IsNil(object.ChainID) {
			args[object.ChainID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &walletR{}
			}

			if !queries.IsNil(obj.ChainID) {
				args[obj.ChainID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`chains`),
		qm.WhereIn(`chains.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Chain")
	}

	var resultSlice []*Chain
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Chain")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for chains")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for chains")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Chain = foreign
		if foreign.R == nil {
			foreign.R = &chainR{}
		}
		foreign.R.Wallets = append(foreign.R.Wallets, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.ChainID, foreign.ID) {
				local.R.Chain = foreign
				if foreign.R == nil {
					foreign.R = &chainR{}
				}
				foreign.R.Wallets = append(foreign.R.Wallets, local)
				break
			}
		}
	}

	return nil
}

// LoadVault allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (walletL) LoadVault(ctx context.Context, e boil.ContextExecutor, singular bool, maybeWallet interface{}, mods queries.Applicator) error {
	var slice []*Wallet
	var object *Wallet

	if singular {
		var ok bool
		object, ok = maybeWallet.(*Wallet)
		if !ok {
			object = new(Wallet)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeWallet)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeWallet))
			}
		}
	} else {
		s, ok := maybeWallet.(*[]*Wallet)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeWallet)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeWallet))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &walletR{}
		}
		if !queries.IsNil(object.VaultID) {
			args[object.VaultID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &walletR{}
			}

			if !queries.IsNil(obj.VaultID) {
				args[obj.VaultID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`vaults`),
		qm.WhereIn(`vaults.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Vault")
	}

	var resultSlice []*Vault
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Vault")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for vaults")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for vaults")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Vault = foreign
		if foreign.R == nil {
			foreign.R = &vaultR{}
		}
		foreign.R.Wallets = append(foreign.R.Wallets, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.VaultID, foreign.ID) {
				local.R.Vault = foreign
				if foreign.R == nil {
					foreign.R = &vaultR{}
				}
				foreign.R.Wallets = append(foreign.R.Wallets, local)
				break
			}
		}
	}

	return nil
}

// LoadSigningRequests allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (walletL) LoadSigningRequests(ctx context.Context, e boil.ContextExecutor, singular bool, maybeWallet interface{}, mods queries.Applicator) error {
	var slice []*Wallet
	var object *Wallet

	if singular {
		var ok bool
		object, ok = maybeWallet.(*Wallet)
		if !ok {
			object = new(Wallet)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeWallet)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeWallet))
			}
		}
	} else {
		s, ok := maybeWallet.(*[]*Wallet)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeWallet)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeWallet))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &walletR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &walletR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`signing_requests`),
		qm.WhereIn(`signing_requests.wallet_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load signing_requests")
	}

	var resultSlice []*SigningRequest
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice signing_requests")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on signing_requests")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for signing_requests")
	}

	if singular {
		object.R.SigningRequests = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &signingRequestR{}
			}
			foreign.R.Wallet = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.WalletID) {
				local.R.SigningRequests = append(local.R.SigningRequests, foreign)
				if foreign.R == nil {
					foreign.R = &signingRequestR{}
				}
				foreign.R.Wallet = local
				break
			}
		}
	}

	return nil
}

// LoadWalletBalances allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (walletL) LoadWalletBalances(ctx context.Context, e boil.ContextExecutor, singular bool, maybeWallet interface{}, mods queries.Applicator) error {
	var slice []*Wallet
	var object *Wallet

	if singular {
		var ok bool
		object, ok = maybeWallet.(*Wallet)
		if !ok {
			object = new(Wallet)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeWallet)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeWallet))
			}
		}
	} else {
		s, ok := maybeWallet.(*[]*Wallet)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeWallet)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeWallet))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &walletR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &walletR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`wallet_balances`),
		qm.WhereIn(`wallet_balances.wallet_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load wallet_balances")
	}

	var resultSlice []*WalletBalance
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice wallet_balances")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on wallet_balances")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for wallet_balances")
	}

	if singular {
		object.R.WalletBalances = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &walletBalanceR{}
			}
			foreign.R.Wallet = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.WalletID) {
				local.R.WalletBalances = append(local.R.WalletBalances, foreign)
				if foreign.R == nil {
					foreign.R = &walletBalanceR{}
				}
				foreign.R.Wallet = local
				break
			}
		}
	}

	return nil
}

// SetChain of the wallet to the related item.
// Sets o.R.Chain to related.
// Adds o to related.R.Wallets.
func (o *Wallet) SetChain(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Chain) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"wallets\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"chain_id"}),
		strmangle.WhereClause("\"", "\"", 2, walletPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.ChainID, related.ID)
	if o.R == nil {
		o.R = &walletR{
			Chain: related,
		}
	} else {
		o.R.Chain = related
	}

	if related.R == nil {
		related.R = &chainR{
			Wallets: WalletSlice{o},
		}
	} else {
		related.R.Wallets = append(related.R.Wallets, o)
	}

	return nil
}

// RemoveChain relationship.
// Sets o.R.Chain to nil.
// Removes o from all passed in related items' relationships struct.
func (o *Wallet) RemoveChain(ctx context.Context, exec boil.ContextExecutor, related *Chain) error {
	var err error

	queries.SetScanner(&o.ChainID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("chain_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.Chain = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.Wallets {
		if queries.Equal(o.ChainID, ri.ChainID) {
			continue
		}

		ln := len(related.R.Wallets)
		if ln > 1 && i < ln-1 {
			related.R.Wallets[i] = related.R.Wallets[ln-1]
		}
		related.R.Wallets = related.R.Wallets[:ln-1]
		break
	}
	return nil
}

// SetVault of the wallet to the related item.
// Sets o.R.Vault to related.
// Adds o to related.R.Wallets.
func (o *Wallet) SetVault(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Vault) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"wallets\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"vault_id"}),
		strmangle.WhereClause("\"", "\"", 2, walletPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.VaultID, related.ID)
	if o.R == nil {
		o.R = &walletR{
			Vault: related,
		}
	} else {
		o.R.Vault = related
	}

	if related.R == nil {
		related.R = &vaultR{
			Wallets: WalletSlice{o},
		}
	} else {
		related.R.Wallets = append(related.R.Wallets, o)
	}

	return nil
}

// RemoveVault relationship.
// Sets o.R.Vault to nil.
// Removes o from all passed in related items' relationships struct.
func (o *Wallet) RemoveVault(ctx context.Context, exec boil.ContextExecutor, related *Vault) error {
	var err error

	queries.SetScanner(&o.VaultID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("vault_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.Vault = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.Wallets {
		if queries.Equal(o.VaultID, ri.VaultID) {
			continue
		}

		ln := len(related.R.Wallets)
		if ln > 1 && i < ln-1 {
			related.R.Wallets[i] = related.R.Wallets[ln-1]
		}
		related.R.Wallets = related.R.Wallets[:ln-1]
		break
	}
	return nil
}

// AddSigningRequests adds the given related objects to the existing relationships
// of the wallet, optionally inserting them as new records.
// Appends related to o.R.SigningRequests.
// Sets related.R.Wallet appropriately.
func (o *Wallet) AddSigningRequests(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*SigningRequest) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.WalletID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"signing_requests\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"wallet_id"}),
				strmangle.WhereClause("\"", "\"", 2, signingRequestPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.WalletID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &walletR{
			SigningRequests: related,
		}
	} else {
		o.R.SigningRequests = append(o.R.SigningRequests, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &signingRequestR{
				Wallet: o,
			}
		} else {
			rel.R.Wallet = o
		}
	}
	return nil
}

// SetSigningRequests removes all previously related items of the
// wallet replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Wallet's SigningRequests accordingly.
// Replaces o.R.SigningRequests with related.
// Sets related.R.Wallet's SigningRequests accordingly.
func (o *Wallet) SetSigningRequests(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*SigningRequest) error {
	query := "update \"signing_requests\" set \"wallet_id\" = null where \"wallet_id\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.SigningRequests {
			queries.SetScanner(&rel.WalletID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.Wallet = nil
		}
		o.R.SigningRequests = nil
	}

	return o.AddSigningRequests(ctx, exec, insert, related...)
}

// RemoveSigningRequests relationships from objects passed in.
// Removes related items from R.SigningRequests (uses pointer comparison, removal does not keep order)
// Sets related.R.Wallet.
func (o *Wallet) RemoveSigningRequests(ctx context.Context, exec boil.ContextExecutor, related ...*SigningRequest) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.WalletID, nil)
		if rel.R != nil {
			rel.R.Wallet = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("wallet_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.SigningRequests {
			if rel != ri {
				continue
			}

			ln := len(o.R.SigningRequests)
			if ln > 1 && i < ln-1 {
				o.R.SigningRequests[i] = o.R.SigningRequests[ln-1]
			}
			o.R.SigningRequests = o.R.SigningRequests[:ln-1]
			break
		}
	}

	return nil
}

// AddWalletBalances adds the given related objects to the existing relationships
// of the wallet, optionally inserting them as new records.
// Appends related to o.R.WalletBalances.
// Sets related.R.Wallet appropriately.
func (o *Wallet) AddWalletBalances(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*WalletBalance) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.WalletID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"wallet_balances\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"wallet_id"}),
				strmangle.WhereClause("\"", "\"", 2, walletBalancePrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.WalletID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &walletR{
			WalletBalances: related,
		}
	} else {
		o.R.WalletBalances = append(o.R.WalletBalances, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &walletBalanceR{
				Wallet: o,
			}
		} else {
			rel.R.Wallet = o
		}
	}
	return nil
}

// SetWalletBalances removes all previously related items of the
// wallet replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Wallet's WalletBalances accordingly.
// Replaces o.R.WalletBalances with related.
// Sets related.R.Wallet's WalletBalances accordingly.
func (o *Wallet) SetWalletBalances(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*WalletBalance) error {
	query := "update \"wallet_balances\" set \"wallet_id\" = null where \"wallet_id\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.WalletBalances {
			queries.SetScanner(&rel.WalletID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.Wallet = nil
		}
		o.R.WalletBalances = nil
	}

	return o.AddWalletBalances(ctx, exec, insert, related...)
}

// RemoveWalletBalances relationships from objects passed in.
// Removes related items from R.WalletBalances (uses pointer comparison, removal does not keep order)
// Sets related.R.Wallet.
func (o *Wallet) RemoveWalletBalances(ctx context.Context, exec boil.ContextExecutor, related ...*WalletBalance) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.WalletID, nil)
		if rel.R != nil {
			rel.R.Wallet = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("wallet_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.WalletBalances {
			if rel != ri {
				continue
			}

			ln := len(o.R.WalletBalances)
			if ln > 1 && i < ln-1 {
				o.R.WalletBalances[i] = o.R.WalletBalances[ln-1]
			}
			o.R.WalletBalances = o.R.WalletBalances[:ln-1]
			break
		}
	}

	return nil
}

// Wallets retrieves all the records using an executor.
func Wallets(mods ...qm.QueryMod) walletQuery {
	mods = append(mods, qm.From("\"wallets\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"wallets\".*"})
	}

	return walletQuery{q}
}

// FindWallet retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindWallet(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*Wallet, error) {
	walletObj := &Wallet{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"wallets\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, walletObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from wallets")
	}

	return walletObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Wallet) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no wallets provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(walletColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	walletInsertCacheMut.RLock()
	cache, cached := walletInsertCache[key]
	walletInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			walletAllColumns,
			walletColumnsWithDefault,
			walletColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(walletType, walletMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(walletType, walletMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"wallets\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"wallets\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into wallets")
	}

	if !cached {
		walletInsertCacheMut.Lock()
		walletInsertCache[key] = cache
		walletInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the Wallet.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Wallet) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	key := makeCacheKey(columns, nil)
	walletUpdateCacheMut.RLock()
	cache, cached := walletUpdateCache[key]
	walletUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			walletAllColumns,
			walletPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update wallets, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"wallets\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, walletPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(walletType, walletMapping, append(wl, walletPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update wallets row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for wallets")
	}

	if !cached {
		walletUpdateCacheMut.Lock()
		walletUpdateCache[key] = cache
		walletUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q walletQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for wallets")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for wallets")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o WalletSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), walletPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"wallets\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, walletPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in wallet slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all wallet")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Wallet) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no wallets provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	nzDefaults := queries.NonZeroDefaultSet(walletColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	walletUpsertCacheMut.RLock()
	cache, cached := walletUpsertCache[key]
	walletUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			walletAllColumns,
			walletColumnsWithDefault,
			walletColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			walletAllColumns,
			walletPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert wallets, could not build update column list")
		}

		ret := strmangle.SetComplement(walletAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(walletPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert wallets, could not build conflict column list")
			}

			conflict = make([]string, len(walletPrimaryKeyColumns))
			copy(conflict, walletPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"wallets\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(walletType, walletMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(walletType, walletMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert wallets")
	}

	if !cached {
		walletUpsertCacheMut.Lock()
		walletUpsertCache[key] = cache
		walletUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single Wallet record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Wallet) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Wallet provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), walletPrimaryKeyMapping)
	sql := "DELETE FROM \"wallets\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from wallets")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for wallets")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q walletQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no walletQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from wallets")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for wallets")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o WalletSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), walletPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"wallets\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, walletPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from wallet slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for wallets")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Wallet) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindWallet(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *WalletSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := WalletSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), walletPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"wallets\".* FROM \"wallets\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, walletPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in WalletSlice")
	}

	*o = slice

	return nil
}

// WalletExists checks if the Wallet row exists.
func WalletExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"wallets\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if wallets exists")
	}

	return exists, nil
}

// Exists checks if the Wallet row exists.
func (o *Wallet) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return WalletExists(ctx, exec, o.ID)
}
