// Code generated by go-swagger; DO NOT EDIT.

package organization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetListOrganizationMembersRouteParams creates a new GetListOrganizationMembersRouteParams object
// no default values defined in spec.
func NewGetListOrganizationMembersRouteParams() GetListOrganizationMembersRouteParams {

	return GetListOrganizationMembersRouteParams{}
}

// GetListOrganizationMembersRouteParams contains all the bound params for the get list organization members route operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetListOrganizationMembersRoute
type GetListOrganizationMembersRouteParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	OrgID string `param:"orgId"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetListOrganizationMembersRouteParams() beforehand.
func (o *GetListOrganizationMembersRouteParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rOrgID, rhkOrgID, _ := route.Params.GetOK("orgId")
	if err := o.bindOrgID(rOrgID, rhkOrgID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetListOrganizationMembersRouteParams) Validate(formats strfmt.Registry) error {
	var res []error

	// orgId
	// Required: true
	// Parameter is provided by construction from the route

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindOrgID binds and validates parameter OrgID from path.
func (o *GetListOrganizationMembersRouteParams) bindOrgID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.OrgID = raw

	return nil
}
