// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: api/v1/auth.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServiceClient interface {
	// Register challenge
	RegisterChallenge(ctx context.Context, in *RegisterChallengeRequest, opts ...grpc.CallOption) (*RegisterChallengeResponse, error)
	// Register verify
	RegisterVerify(ctx context.Context, in *RegisterVerifyRequest, opts ...grpc.CallOption) (*RegisterVerifyResponse, error)
	// Login challenge
	LoginChallenge(ctx context.Context, in *LoginChallengeRequest, opts ...grpc.CallOption) (*LoginChallengeResponse, error)
	// Login verify
	LoginVerify(ctx context.Context, in *LoginVerifyRequest, opts ...grpc.CallOption) (*LoginVerifyResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) RegisterChallenge(ctx context.Context, in *RegisterChallengeRequest, opts ...grpc.CallOption) (*RegisterChallengeResponse, error) {
	out := new(RegisterChallengeResponse)
	err := c.cc.Invoke(ctx, "/api.v1.AuthService/RegisterChallenge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RegisterVerify(ctx context.Context, in *RegisterVerifyRequest, opts ...grpc.CallOption) (*RegisterVerifyResponse, error) {
	out := new(RegisterVerifyResponse)
	err := c.cc.Invoke(ctx, "/api.v1.AuthService/RegisterVerify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) LoginChallenge(ctx context.Context, in *LoginChallengeRequest, opts ...grpc.CallOption) (*LoginChallengeResponse, error) {
	out := new(LoginChallengeResponse)
	err := c.cc.Invoke(ctx, "/api.v1.AuthService/LoginChallenge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) LoginVerify(ctx context.Context, in *LoginVerifyRequest, opts ...grpc.CallOption) (*LoginVerifyResponse, error) {
	out := new(LoginVerifyResponse)
	err := c.cc.Invoke(ctx, "/api.v1.AuthService/LoginVerify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility
type AuthServiceServer interface {
	// Register challenge
	RegisterChallenge(context.Context, *RegisterChallengeRequest) (*RegisterChallengeResponse, error)
	// Register verify
	RegisterVerify(context.Context, *RegisterVerifyRequest) (*RegisterVerifyResponse, error)
	// Login challenge
	LoginChallenge(context.Context, *LoginChallengeRequest) (*LoginChallengeResponse, error)
	// Login verify
	LoginVerify(context.Context, *LoginVerifyRequest) (*LoginVerifyResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (UnimplementedAuthServiceServer) RegisterChallenge(context.Context, *RegisterChallengeRequest) (*RegisterChallengeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterChallenge not implemented")
}
func (UnimplementedAuthServiceServer) RegisterVerify(context.Context, *RegisterVerifyRequest) (*RegisterVerifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterVerify not implemented")
}
func (UnimplementedAuthServiceServer) LoginChallenge(context.Context, *LoginChallengeRequest) (*LoginChallengeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginChallenge not implemented")
}
func (UnimplementedAuthServiceServer) LoginVerify(context.Context, *LoginVerifyRequest) (*LoginVerifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginVerify not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_RegisterChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RegisterChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.AuthService/RegisterChallenge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RegisterChallenge(ctx, req.(*RegisterChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RegisterVerify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterVerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RegisterVerify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.AuthService/RegisterVerify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RegisterVerify(ctx, req.(*RegisterVerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_LoginChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).LoginChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.AuthService/LoginChallenge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).LoginChallenge(ctx, req.(*LoginChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_LoginVerify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginVerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).LoginVerify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.AuthService/LoginVerify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).LoginVerify(ctx, req.(*LoginVerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterChallenge",
			Handler:    _AuthService_RegisterChallenge_Handler,
		},
		{
			MethodName: "RegisterVerify",
			Handler:    _AuthService_RegisterVerify_Handler,
		},
		{
			MethodName: "LoginChallenge",
			Handler:    _AuthService_LoginChallenge_Handler,
		},
		{
			MethodName: "LoginVerify",
			Handler:    _AuthService_LoginVerify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/auth.proto",
}
