// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: api/v1/signing.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SigningServiceClient is the client API for SigningService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SigningServiceClient interface {
	// Create a signing request (requires Passkey signature)
	CreateRequest(ctx context.Context, in *CreateSigningRequest, opts ...grpc.CallOption) (*CreateSigningResponse, error)
	// Approve a signing request (requires Passkey signature)
	ApproveRequest(ctx context.Context, in *ApproveSigningRequest, opts ...grpc.CallOption) (*ApproveSigningResponse, error)
	// List signing requests
	ListRequests(ctx context.Context, in *ListSigningRequestsRequest, opts ...grpc.CallOption) (*ListSigningRequestsResponse, error)
}

type signingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSigningServiceClient(cc grpc.ClientConnInterface) SigningServiceClient {
	return &signingServiceClient{cc}
}

func (c *signingServiceClient) CreateRequest(ctx context.Context, in *CreateSigningRequest, opts ...grpc.CallOption) (*CreateSigningResponse, error) {
	out := new(CreateSigningResponse)
	err := c.cc.Invoke(ctx, "/api.v1.SigningService/CreateRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signingServiceClient) ApproveRequest(ctx context.Context, in *ApproveSigningRequest, opts ...grpc.CallOption) (*ApproveSigningResponse, error) {
	out := new(ApproveSigningResponse)
	err := c.cc.Invoke(ctx, "/api.v1.SigningService/ApproveRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signingServiceClient) ListRequests(ctx context.Context, in *ListSigningRequestsRequest, opts ...grpc.CallOption) (*ListSigningRequestsResponse, error) {
	out := new(ListSigningRequestsResponse)
	err := c.cc.Invoke(ctx, "/api.v1.SigningService/ListRequests", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SigningServiceServer is the server API for SigningService service.
// All implementations must embed UnimplementedSigningServiceServer
// for forward compatibility
type SigningServiceServer interface {
	// Create a signing request (requires Passkey signature)
	CreateRequest(context.Context, *CreateSigningRequest) (*CreateSigningResponse, error)
	// Approve a signing request (requires Passkey signature)
	ApproveRequest(context.Context, *ApproveSigningRequest) (*ApproveSigningResponse, error)
	// List signing requests
	ListRequests(context.Context, *ListSigningRequestsRequest) (*ListSigningRequestsResponse, error)
	mustEmbedUnimplementedSigningServiceServer()
}

// UnimplementedSigningServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSigningServiceServer struct {
}

func (UnimplementedSigningServiceServer) CreateRequest(context.Context, *CreateSigningRequest) (*CreateSigningResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRequest not implemented")
}
func (UnimplementedSigningServiceServer) ApproveRequest(context.Context, *ApproveSigningRequest) (*ApproveSigningResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApproveRequest not implemented")
}
func (UnimplementedSigningServiceServer) ListRequests(context.Context, *ListSigningRequestsRequest) (*ListSigningRequestsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRequests not implemented")
}
func (UnimplementedSigningServiceServer) mustEmbedUnimplementedSigningServiceServer() {}

// UnsafeSigningServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SigningServiceServer will
// result in compilation errors.
type UnsafeSigningServiceServer interface {
	mustEmbedUnimplementedSigningServiceServer()
}

func RegisterSigningServiceServer(s grpc.ServiceRegistrar, srv SigningServiceServer) {
	s.RegisterService(&SigningService_ServiceDesc, srv)
}

func _SigningService_CreateRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSigningRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SigningServiceServer).CreateRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.SigningService/CreateRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SigningServiceServer).CreateRequest(ctx, req.(*CreateSigningRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SigningService_ApproveRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveSigningRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SigningServiceServer).ApproveRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.SigningService/ApproveRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SigningServiceServer).ApproveRequest(ctx, req.(*ApproveSigningRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SigningService_ListRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSigningRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SigningServiceServer).ListRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.SigningService/ListRequests",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SigningServiceServer).ListRequests(ctx, req.(*ListSigningRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SigningService_ServiceDesc is the grpc.ServiceDesc for SigningService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SigningService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.SigningService",
	HandlerType: (*SigningServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRequest",
			Handler:    _SigningService_CreateRequest_Handler,
		},
		{
			MethodName: "ApproveRequest",
			Handler:    _SigningService_ApproveRequest_Handler,
		},
		{
			MethodName: "ListRequests",
			Handler:    _SigningService_ListRequests_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/signing.proto",
}
