// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: infra/v1/backup.proto

package infra

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BackupServiceClient is the client API for BackupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BackupServiceClient interface {
	// 恢复MPC分片（从SSS备份分片）
	RecoverMPCShare(ctx context.Context, in *RecoverMPCShareRequest, opts ...grpc.CallOption) (*RecoverMPCShareResponse, error)
	// 获取备份状态
	GetBackupStatus(ctx context.Context, in *GetBackupStatusRequest, opts ...grpc.CallOption) (*GetBackupStatusResponse, error)
	// 列出备份分片
	ListBackupShares(ctx context.Context, in *ListBackupSharesRequest, opts ...grpc.CallOption) (*ListBackupSharesResponse, error)
}

type backupServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBackupServiceClient(cc grpc.ClientConnInterface) BackupServiceClient {
	return &backupServiceClient{cc}
}

func (c *backupServiceClient) RecoverMPCShare(ctx context.Context, in *RecoverMPCShareRequest, opts ...grpc.CallOption) (*RecoverMPCShareResponse, error) {
	out := new(RecoverMPCShareResponse)
	err := c.cc.Invoke(ctx, "/infra.v1.BackupService/RecoverMPCShare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupServiceClient) GetBackupStatus(ctx context.Context, in *GetBackupStatusRequest, opts ...grpc.CallOption) (*GetBackupStatusResponse, error) {
	out := new(GetBackupStatusResponse)
	err := c.cc.Invoke(ctx, "/infra.v1.BackupService/GetBackupStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupServiceClient) ListBackupShares(ctx context.Context, in *ListBackupSharesRequest, opts ...grpc.CallOption) (*ListBackupSharesResponse, error) {
	out := new(ListBackupSharesResponse)
	err := c.cc.Invoke(ctx, "/infra.v1.BackupService/ListBackupShares", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackupServiceServer is the server API for BackupService service.
// All implementations must embed UnimplementedBackupServiceServer
// for forward compatibility
type BackupServiceServer interface {
	// 恢复MPC分片（从SSS备份分片）
	RecoverMPCShare(context.Context, *RecoverMPCShareRequest) (*RecoverMPCShareResponse, error)
	// 获取备份状态
	GetBackupStatus(context.Context, *GetBackupStatusRequest) (*GetBackupStatusResponse, error)
	// 列出备份分片
	ListBackupShares(context.Context, *ListBackupSharesRequest) (*ListBackupSharesResponse, error)
	mustEmbedUnimplementedBackupServiceServer()
}

// UnimplementedBackupServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBackupServiceServer struct {
}

func (UnimplementedBackupServiceServer) RecoverMPCShare(context.Context, *RecoverMPCShareRequest) (*RecoverMPCShareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecoverMPCShare not implemented")
}
func (UnimplementedBackupServiceServer) GetBackupStatus(context.Context, *GetBackupStatusRequest) (*GetBackupStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBackupStatus not implemented")
}
func (UnimplementedBackupServiceServer) ListBackupShares(context.Context, *ListBackupSharesRequest) (*ListBackupSharesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBackupShares not implemented")
}
func (UnimplementedBackupServiceServer) mustEmbedUnimplementedBackupServiceServer() {}

// UnsafeBackupServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackupServiceServer will
// result in compilation errors.
type UnsafeBackupServiceServer interface {
	mustEmbedUnimplementedBackupServiceServer()
}

func RegisterBackupServiceServer(s grpc.ServiceRegistrar, srv BackupServiceServer) {
	s.RegisterService(&BackupService_ServiceDesc, srv)
}

func _BackupService_RecoverMPCShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecoverMPCShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).RecoverMPCShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infra.v1.BackupService/RecoverMPCShare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).RecoverMPCShare(ctx, req.(*RecoverMPCShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupService_GetBackupStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBackupStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).GetBackupStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infra.v1.BackupService/GetBackupStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).GetBackupStatus(ctx, req.(*GetBackupStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupService_ListBackupShares_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBackupSharesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).ListBackupShares(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infra.v1.BackupService/ListBackupShares",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).ListBackupShares(ctx, req.(*ListBackupSharesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BackupService_ServiceDesc is the grpc.ServiceDesc for BackupService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BackupService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "infra.v1.BackupService",
	HandlerType: (*BackupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecoverMPCShare",
			Handler:    _BackupService_RecoverMPCShare_Handler,
		},
		{
			MethodName: "GetBackupStatus",
			Handler:    _BackupService_GetBackupStatus_Handler,
		},
		{
			MethodName: "ListBackupShares",
			Handler:    _BackupService_ListBackupShares_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "infra/v1/backup.proto",
}

// BackupDeliveryServiceClient is the client API for BackupDeliveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BackupDeliveryServiceClient interface {
	// 请求分片下发
	RequestShareDelivery(ctx context.Context, in *ShareDeliveryRequest, opts ...grpc.CallOption) (*ShareDeliveryResponse, error)
	// 确认分片接收
	ConfirmShareDelivery(ctx context.Context, in *ShareConfirmationRequest, opts ...grpc.CallOption) (*ShareConfirmationResponse, error)
	// 查询分片状态
	QueryShareStatus(ctx context.Context, in *ShareStatusQuery, opts ...grpc.CallOption) (*ShareStatusResponse, error)
}

type backupDeliveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBackupDeliveryServiceClient(cc grpc.ClientConnInterface) BackupDeliveryServiceClient {
	return &backupDeliveryServiceClient{cc}
}

func (c *backupDeliveryServiceClient) RequestShareDelivery(ctx context.Context, in *ShareDeliveryRequest, opts ...grpc.CallOption) (*ShareDeliveryResponse, error) {
	out := new(ShareDeliveryResponse)
	err := c.cc.Invoke(ctx, "/infra.v1.BackupDeliveryService/RequestShareDelivery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupDeliveryServiceClient) ConfirmShareDelivery(ctx context.Context, in *ShareConfirmationRequest, opts ...grpc.CallOption) (*ShareConfirmationResponse, error) {
	out := new(ShareConfirmationResponse)
	err := c.cc.Invoke(ctx, "/infra.v1.BackupDeliveryService/ConfirmShareDelivery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupDeliveryServiceClient) QueryShareStatus(ctx context.Context, in *ShareStatusQuery, opts ...grpc.CallOption) (*ShareStatusResponse, error) {
	out := new(ShareStatusResponse)
	err := c.cc.Invoke(ctx, "/infra.v1.BackupDeliveryService/QueryShareStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackupDeliveryServiceServer is the server API for BackupDeliveryService service.
// All implementations must embed UnimplementedBackupDeliveryServiceServer
// for forward compatibility
type BackupDeliveryServiceServer interface {
	// 请求分片下发
	RequestShareDelivery(context.Context, *ShareDeliveryRequest) (*ShareDeliveryResponse, error)
	// 确认分片接收
	ConfirmShareDelivery(context.Context, *ShareConfirmationRequest) (*ShareConfirmationResponse, error)
	// 查询分片状态
	QueryShareStatus(context.Context, *ShareStatusQuery) (*ShareStatusResponse, error)
	mustEmbedUnimplementedBackupDeliveryServiceServer()
}

// UnimplementedBackupDeliveryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBackupDeliveryServiceServer struct {
}

func (UnimplementedBackupDeliveryServiceServer) RequestShareDelivery(context.Context, *ShareDeliveryRequest) (*ShareDeliveryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestShareDelivery not implemented")
}
func (UnimplementedBackupDeliveryServiceServer) ConfirmShareDelivery(context.Context, *ShareConfirmationRequest) (*ShareConfirmationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmShareDelivery not implemented")
}
func (UnimplementedBackupDeliveryServiceServer) QueryShareStatus(context.Context, *ShareStatusQuery) (*ShareStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryShareStatus not implemented")
}
func (UnimplementedBackupDeliveryServiceServer) mustEmbedUnimplementedBackupDeliveryServiceServer() {}

// UnsafeBackupDeliveryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackupDeliveryServiceServer will
// result in compilation errors.
type UnsafeBackupDeliveryServiceServer interface {
	mustEmbedUnimplementedBackupDeliveryServiceServer()
}

func RegisterBackupDeliveryServiceServer(s grpc.ServiceRegistrar, srv BackupDeliveryServiceServer) {
	s.RegisterService(&BackupDeliveryService_ServiceDesc, srv)
}

func _BackupDeliveryService_RequestShareDelivery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareDeliveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupDeliveryServiceServer).RequestShareDelivery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infra.v1.BackupDeliveryService/RequestShareDelivery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupDeliveryServiceServer).RequestShareDelivery(ctx, req.(*ShareDeliveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupDeliveryService_ConfirmShareDelivery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareConfirmationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupDeliveryServiceServer).ConfirmShareDelivery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infra.v1.BackupDeliveryService/ConfirmShareDelivery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupDeliveryServiceServer).ConfirmShareDelivery(ctx, req.(*ShareConfirmationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupDeliveryService_QueryShareStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareStatusQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupDeliveryServiceServer).QueryShareStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infra.v1.BackupDeliveryService/QueryShareStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupDeliveryServiceServer).QueryShareStatus(ctx, req.(*ShareStatusQuery))
	}
	return interceptor(ctx, in, info, handler)
}

// BackupDeliveryService_ServiceDesc is the grpc.ServiceDesc for BackupDeliveryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BackupDeliveryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "infra.v1.BackupDeliveryService",
	HandlerType: (*BackupDeliveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestShareDelivery",
			Handler:    _BackupDeliveryService_RequestShareDelivery_Handler,
		},
		{
			MethodName: "ConfirmShareDelivery",
			Handler:    _BackupDeliveryService_ConfirmShareDelivery_Handler,
		},
		{
			MethodName: "QueryShareStatus",
			Handler:    _BackupDeliveryService_QueryShareStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "infra/v1/backup.proto",
}
