// Code generated by go run -tags scripts scripts/handlers/gen_handlers.go; DO NOT EDIT.
package handlers

import (
	"github.com/kashguard/go-mpc-vault/internal/api"
	"github.com/kashguard/go-mpc-vault/internal/api/handlers/auth"
	"github.com/kashguard/go-mpc-vault/internal/api/handlers/common"
	"github.com/kashguard/go-mpc-vault/internal/api/handlers/organization"
	"github.com/kashguard/go-mpc-vault/internal/api/handlers/push"
	"github.com/kashguard/go-mpc-vault/internal/api/handlers/signing"
	"github.com/kashguard/go-mpc-vault/internal/api/handlers/vault"
	"github.com/kashguard/go-mpc-vault/internal/api/handlers/wellknown"
	"github.com/labstack/echo/v4"
)

func AttachAllRoutes(s *api.Server) {
	// attach our routes
	s.Router.Routes = []*echo.Route{
		auth.DeleteUserAccountRoute(s),
		auth.GetCompleteRegisterRoute(s),
		auth.GetUserInfoRoute(s),
		auth.PostChangePasswordRoute(s),
		auth.PostCompleteRegisterRoute(s),
		auth.PostForgotPasswordCompleteRoute(s),
		auth.PostForgotPasswordRoute(s),
		auth.PostLoginRoute(s),
		auth.PostLogoutRoute(s),
		auth.PostRefreshRoute(s),
		auth.PostRegisterRoute(s),
		common.GetHealthyRoute(s),
		common.GetReadyRoute(s),
		common.GetSwaggerRoute(s),
		common.GetVersionRoute(s),
	organization.DeleteOrganizationMemberRoute(s),
	organization.GetListOrganizationMembersRoute(s),
	organization.GetListOrganizationsRoute(s),
	organization.PostAddOrganizationMemberRoute(s),
	organization.PostCreateOrganizationRoute(s),
		signing.GetListSigningRequestsRoute(s),
	push.PutUpdatePushTokenRoute(s),
	signing.PostApproveSigningRequestRoute(s),
	signing.PostCreateSigningRequestRoute(s),
	vault.PostCreateVaultRoute(s),
	vault.PostCreateWalletRoute(s),
		wellknown.GetAndroidDigitalAssetLinksRoute(s),
		wellknown.GetAppleAppSiteAssociationRoute(s),
	}
}
